Workflow
umbraco/UmbracoDocs pull request #2761
Opened 2020-10-09 09:17 UTC by ctf-umbraco

2020-10-09 12:39 UTC, Jay-umbr requested changes
Lengthy article, so I had suggested some changes - mostly how I would phrase some things, and fixed 2-3 grammar mistakes too. Quite a nice thing, overall!

2020-10-09 12:39 UTC, Jay-umbr commented on Umbraco-Uno/Creating-Content/index.md
> +If you are new to Umbraco Forms and want to learn more about how to work with them then you can read more about them in the Working with Forms section.
```suggestion
If you are new to Umbraco Forms, and want to learn more about how to work with them, you can read more about the workflow in the Working with Forms section.
```

2020-10-09 12:39 UTC, Jay-umbr commented on Umbraco-Uno/Widgets/Umbraco-Form/index.md
> +You can create a form by selecting the Forms section in the top menu in your backoffice. Learn more about how to create forms in the [Working with Forms](../../Working-with-Forms) section.
```suggestion
You can create a form by navigating to the Forms section in the top menu of your backoffice. Learn more about how to create forms in the [Working with Forms](../../Working-with-Forms) section.
```

2020-10-09 12:39 UTC, Jay-umbr commented on Umbraco-Uno/Working-with-Forms/Replies/index.md
>  If you have more then one form, there will be a box for each of the forms. If you have more then four forms, you will have the option to ***show all*** as only four will be shown as default.
```suggestion
If you have more than one form, there will be a box for each of the forms. If you have more than four forms, you will have the option to ***show all*** as only four will be shown as default. 
```

2020-10-09 12:39 UTC, Jay-umbr commented on Umbraco-Uno/Working-with-Forms/Umbraco-Forms-widget/index.md
You say "in the next article", but is it going to be on the same page? If the link just before that points to the article you mentioned  I would just remove "from your form which is the next article" part

2020-10-09 12:39 UTC, Jay-umbr commented on Umbraco-Uno/Working-with-Forms/workflow/index.md
> +A workflow, in this case, is the flow that happens from you press the submit form button on the frontend until it ends in your email (or wherever you assigned it to arrive)
```suggestion
A workflow, in this case, is the flow that starts when you press the "submit form" button on the frontend, and ends with the form reply being sent to your email (or wherever you assigned it to arrive)
```

2020-10-09 12:39 UTC, Jay-umbr commented on Umbraco-Uno/Working-with-Forms/workflow/index.md
> +The most common Workflow is to have the user press the submit button, then a thank you message pops up, and then the email is sent to a designated mail inbox. However, you could choose to have it sen
```suggestion
The most common Workflow is to have the user press the submit button, present a thank you message, and then send the email to a designated mail inbox. However, you could choose to have it sent to, for example, a Slack channel if you wanted. In this guide, you will learn to set-up a basic workflow for your forms.
```

2020-10-09 12:39 UTC, Jay-umbr commented on Umbraco-Uno/Working-with-Forms/workflow/index.md
> +This requires you to have set up a form if you dont have a form set-up yet you can learn how to do that in the [Setting up a form](../Setting-up-a-form/index.md) setion.
```suggestion
This requires you to have set up a form. If you don't have a form set-up yet, you can learn how to do that in the [Setting up a form](../Setting-up-a-form/index.md) section.
```

2020-10-09 12:39 UTC, Jay-umbr commented on Umbraco-Uno/Working-with-Forms/workflow/index.md
> +1. In the Forms section of the backoffice.
```suggestion
1. Navigate to the Forms section of the backoffice.
```

2020-10-09 12:39 UTC, Jay-umbr commented on Umbraco-Uno/Working-with-Forms/workflow/index.md
> +In this section, we will make the Workflow send to your email of choice. Please note that this is for a workflow that contains a template. To set up the one without a template, it is the same except
```suggestion
In this section, we will make the Workflow send an email to your inbox of choice. Please note that this is for a workflow that contains a template. To set up the one without a template, it is the same approach except for the 8th step.
```

2020-10-16 08:08 UTC, sofietoft requested changes
I've made some suggestions.
Please take a look when you have time.

2020-10-16 08:08 UTC, sofietoft commented on Umbraco-Uno/Working-with-Forms/Workflow/index.md
> +2. In the field called ***Sender email***, you should add something like Noreply@something.something.
```suggestion
2. In the field called ***Sender email***, you should add something like Noreply@something.something
```

2020-10-16 08:08 UTC, sofietoft commented on Umbraco-Uno/Working-with-Forms/Workflow/index.md
> +4. Hit submit and then hit submit in the next menu as well
Would be good with a quick ending to this.

2020-10-16 08:08 UTC, sofietoft commented on Umbraco-Uno/Working-with-Forms/Workflow/index.md
> +5. Next up is the ***Sender Email*** here. You can add something like Noreply@something.com.
```suggestion
5. Next up is the ***Sender Email***. Here you can add something like Noreply@something.com.
```

2020-10-16 08:08 UTC, sofietoft commented on Umbraco-Uno/Working-with-Forms/Workflow/index.md
> +9. Finally, leave ***Attachments*** unchecked unless you need the users to send attachments to your inbox.
```suggestion
9. Finally, leave ***Attachments*** unchecked, unless you have an upload-field in the form, and want to receive the uploaded files through the workflow.
```

2020-10-16 08:08 UTC, sofietoft commented on Umbraco-Uno/Working-with-Forms/Workflow/index.md
> +3. The ***Include Sensitive Data*** will be left unchecked.
```suggestion
3. The ***Include Sensitive Data*** will be left unchecked unless your form contains sensitive data.
```

2020-10-16 08:08 UTC, sofietoft commented on Umbraco-Uno/Working-with-Forms/index.md
> +Here you can learn how to work with the excisting workflow or create your own.
```suggestion
Here you can learn how to work with workflows, and decide what should happen once visitors on your site fill in a form.
```

2020-10-19 05:33 UTC, merged