Add value to checkbox property editor
umbraco/UmbracoDocs pull request #2823
Opened 2020-10-28 15:39 UTC by erikjanwestendorp

Belongs to https://github.com/umbraco/UmbracoDocs/issues/2714

2020-10-30 07:37 UTC, sofietoft commented
Looks great @erikjanwestendorp !

Thanks for adding this 💪 
I'll make sure it is reviewed as soon as possible!

2020-11-03 14:32 UTC, sofietoft requested changes
The code samples looks great @erikjanwestendorp !

Would you be up for adding the GUID samples, like it's been done here as well: https://our.umbraco.com/documentation/Reference/Management/Services/ContentTypeService/Retrieving-content-types

2020-11-03 14:32 UTC, sofietoft commented on Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/True-False/index.md
> +var content = _contentService.GetById(1234); // ID of your page
```suggestion
var content = contentService.GetById(1234); // ID of your page
```

2020-11-04 07:03 UTC, erikjanwestendorp commented
@sofietoft Thanks for the suggestion. I Just committed an example with the use of a GUID

2020-11-04 07:59 UTC, sofietoft approved these changes
Looks great @erikjanwestendorp !

Thanks for adding the GUID in there as well, and for showing both ways to do it 💪 
Much appreciated.
Let's get this merged in then 😄

2020-11-04 08:00 UTC, merged