New User deploy permissions
umbraco/UmbracoDocs pull request #2848
Opened 2020-11-02 10:41 UTC by jonat123

New article describing the new permissions for users and deploy

2020-11-02 10:55 UTC, Jay-umbr reviewed
Some grammar mistakes present. I suggested changes. Otherwise - a very good article

2020-11-02 10:55 UTC, Jay-umbr commented on Umbraco-Cloud/Deployment/Users-On-Cloud/index.md
> +From here you are able to either create a new or edit an existing User Group.
```suggestion
From here you are able to either create a new User Group, or edit an existing one.
```

2020-11-02 10:55 UTC, Jay-umbr commented on Umbraco-Cloud/Deployment/Users-On-Cloud/index.md
> +You can decide whether the users in the new User Group can restore, restore partial or transfer content.
```suggestion
You can decide whether the users in the new User Group can restore, partially restore, or transfer content.
```

2020-11-02 10:55 UTC, Jay-umbr commented on Umbraco-Cloud/Deployment/Users-On-Cloud/index.md
> +To edit an already existing user group go to the User group you want to edit, e.g Editors or Writers and set the permissions from there.
```suggestion
To edit an already existing user group, go to the User group you want to edit, e.g Editors or Writers, and set the permissions from there.
```

2020-11-02 10:55 UTC, Jay-umbr commented on Umbraco-Cloud/Deployment/Users-On-Cloud/index.md
> +When you click add, you can choose which content node on your project that you want to set the Granular settings for.
```suggestion
When you click "add", you can choose which content node on your project that you want to set the Granular settings for.
```

2020-11-02 10:55 UTC, Jay-umbr commented on Umbraco-Cloud/Deployment/Users-On-Cloud/index.md
> +When you have choosen the node that you want to set the settings for, you can then set the permissions for restore, partial restore and queueing content for transfer.
```suggestion
When you have chosen the node that you want to set the settings for, you can then set the permissions for restore, partial restore, and queueing content for transfer.
```

2020-11-02 12:00 UTC, sofietoft requested changes
Super article, @jonat123 !

Be careful of the grammar ;)
And also, make sure you're consistent with capitalizing names and specific Umbraco terms.
I've made some suggestions - let me know what you think!

2020-11-09 14:21 UTC, Jay-umbr requested changes
Made suggestions. Some minor mistakes. Some stuff is phrased in a weird way

2020-11-09 14:21 UTC, Jay-umbr commented on Umbraco-Cloud/Deployment/Users-On-Cloud/index.md
> +On Umbraco Cloud, users work almost identical as they do on a normal installation of Umbraco, however, you have a few more settings available for the backoffice users on Umbraco Cloud.
```suggestion
On Umbraco Cloud, users work in almost the same way as on a normal installation of Umbraco; however, there are a few more settings available for the backoffice users on Umbraco Cloud.
```

2020-11-09 14:21 UTC, Jay-umbr commented on Umbraco-Cloud/Deployment/Users-On-Cloud/index.md
> +In this article, we will show how users work and the different settings on Umbraco Cloud.
```suggestion
In this article, we will show how users work on Umbraco Cloud, as well as explain the different settings for users.
```

2020-11-09 14:21 UTC, Jay-umbr commented on Umbraco-Cloud/Deployment/Users-On-Cloud/index.md
> +They will by default when added to the project as a team member be added to the backoffice as administrators.
```suggestion
By default, when added to the project as a team member, they will be added to the backoffice as administrators.
```

2020-11-09 14:21 UTC, Jay-umbr commented on Umbraco-Cloud/Deployment/Users-On-Cloud/index.md
> +users can also be invited directly from the backoffice of your Umbraco Cloud project where you can give them different user permissions.
```suggestion
Users can also be invited directly from the backoffice of your Umbraco Cloud project, from where you can give them different permissions.
```

2020-11-09 14:21 UTC, Jay-umbr commented on Umbraco-Cloud/Deployment/Users-On-Cloud/index.md
> +users are environment-specific on Umbraco Cloud, this means that they will not be transferred over when doing a deployment to the next environment, this means that they will need to be added on the d
```suggestion
Users are environment-specific on Umbraco Cloud. This means that they will not be transferred over when doing a deployment to the next environment - they will need to be added on the different environments on Umbraco Cloud.
```

2020-11-09 14:21 UTC, Jay-umbr commented on Umbraco-Cloud/Deployment/Users-On-Cloud/index.md
> +A feature on Umbraco Cloud is the possibility to control which users have access to transferring and restoring content and media on your Umbraco Cloud project.
```suggestion
On Umbraco Cloud, it is possible to control which users have access to transferring and restoring content and media on your Umbraco Cloud project.
```

2020-11-09 14:21 UTC, Jay-umbr commented on Umbraco-Cloud/Deployment/Users-On-Cloud/index.md
> +You have the option to decide whether a specific User Group has permission to do a restore, partial restore or if they can queue content for transfer to the next environment.
```suggestion
You have the option to decide whether a specific User Group has permission to do a restore, partial restore, or queue content for transfer to the next environment.
```

2020-11-09 14:21 UTC, Jay-umbr commented on Umbraco-Cloud/Deployment/Users-On-Cloud/index.md
> +In the bottom of the User Group, you can add the setting for Granular permission for your content nodes.
```suggestion
At the bottom of the User Group, you can add the setting for Granular permission for your content nodes.
```

2020-11-09 14:21 UTC, Jay-umbr commented on Umbraco-Cloud/Deployment/Users-On-Cloud/index.md
> +When you click "Add", you can choose which content node on your project that you want to set the Granular settings for.
```suggestion
When you click "Add", you can choose the content node which you want to set the Granular settings for.
```

2020-11-10 07:58 UTC, sofietoft requested changes
Great article @jonat123 !

I've added some more comments.
Also, how about adding the steps to set permissions (lines 40 to 48ish), into a list instead?
That would make it easier to follow the steps, I think 🤔 
What do you think?

2020-11-10 07:58 UTC, sofietoft commented on Umbraco-Cloud/Set-Up/Users-On-Cloud/index.md
> +:::note
Should we add to this note, that if they're added as Team Members then they will be added to ALL environments?

2020-11-10 07:58 UTC, sofietoft commented on Umbraco-Cloud/Set-Up/Users-On-Cloud/index.md
> +In the right corner, you need to click on "Groups", from here you are able to either create a new User Group or edit an existing one.
```suggestion
In the right corner, you need to click on "Groups", and from here you are able to either create a new User Group or edit an existing one.
```

2020-11-10 07:58 UTC, sofietoft commented on Umbraco-Cloud/Set-Up/Users-On-Cloud/index.md
> +You can set the permission when you are creating or editing an existing user group.
```suggestion
You can set the permission when you are creating or editing an existing User Group.
```

2020-11-10 08:08 UTC, sofietoft commented
Forgot to mention one thing:
When creating **new** articles on the docs - make sure you add YAML tags to the very beginning of the article.
See more here: https://our.umbraco.com/documentation/Contribute/File-Naming-Conventions/#adding-meta-data

2020-11-16 12:03 UTC, sofietoft reviewed
Juuuust a few mionr things 😁

2020-11-16 12:03 UTC, sofietoft commented on Umbraco-Cloud/Set-Up/Users-On-Cloud/index.md
> +As mentioned it is also possible to set Granular permissions for a specific content node on your cloud project.
```suggestion
As mentioned it is also possible to set Granular permissions for a specific content node on your Cloud project.
```

2020-11-16 13:42 UTC, merged