Update UmbracoServices to v9
umbraco/UmbracoDocs pull request #3272
Opened 2021-06-14 14:57 UTC by elit0451

## Details

- index-v9.md 
  - Changed code snippets and wording 
  - Some of the links at the bottom of index-v9.md are not changed as the articles have not been migrated + Umbraco TV videos are about v7

</br>

Articles under services available:
* AuditService
  - removed **Services property** as it uses `Services` property which we no longer use
  - removed **Static accessor** section as it was using `Current` which we don't have any more

* ConsentService

* ContentService

* ContentTypeService

* ApplicationTreeService
  - removed - was dealing with tree registrations in the ~/Config/trees.config file (not working with such file anymore)

* DataTypeService
  - removed **Services property** as it uses `Services` property which we no longer use
  - removed **Static accessor** section as it was using `Current` which we don't have any more

* EntityService
  - removed **Services property** as it uses `Services` property which we no longer use
  - removed **Static accessor** section as it was using `Current` which we don't have any more

* FileService
  - removed **Services property** as it uses `Services` property which we no longer use
  - removed **Static accessor** section as it was using `Current` which we don't have any more

* LocalizationService
  - removed **Services property** as it uses `Services` property which we no longer use
  - removed **Static accessor** section as it was using `Current` which we don't have any more
 
*  MacroService
   - removed **Services property** as it uses `Services` property which we no longer use
   - removed **Static accessor** section as it was using `Current` which we don't have any more

* MediaService
  - removed **Services property** as it uses `Services` property which we no longer use
  - removed **Static accessor** section as it was using `Current` which we don't have anymore
  - check code snippet from **Creating a new media from an uploaded file** and note ❗ ❗  (the only thing that needs to be updated in order to completely mark the article as updated)

* MemberService
 
* MemberTypeService

* MemberGroupService

2021-06-15 19:02 UTC, bergmania requested changes
Here is my suggested changes.. What do you think @jonat123

2021-06-16 07:25 UTC, jonat123 reviewed
@elit0451 Looks good, I made a suggestion that we remove the V7 videos as it makes no sense to have v7 videos in a v9 article, furthermore, we are closing down Umbraco TV and moving to youtube so the links won't work in the future anyway.

@bergmania I like your suggestions so I have committed them to the PR :)

2021-06-16 07:25 UTC, jonat123 commented on Fundamentals/Code/Umbraco-Services/index-v9.md
> +- [Chapter: Member API](https://umbraco.tv/videos/umbraco-v7/developer/fundamentals/member-api/)
```suggestion

```

2021-06-16 07:25 UTC, jonat123 commented on Fundamentals/Code/Umbraco-Services/index-v9.md
> +- [Chapter: Member API](https://umbraco.tv/videos/umbraco-v7/developer/fundamentals/member-api/)
Lets just remove the videos for V7, as i don't think it makes sense that we have videos for V7 in a article for V9, plus we are going to move away from Umbraco TV anyways so the links wont work anyways

2021-06-16 07:35 UTC, bergmania approved these changes

2021-06-16 07:36 UTC, bergmania commented
All good.. Elitsa is on vacation, so I approved your suggestion.. IMO this is ready to merge.

2021-06-16 07:44 UTC, jonat123 commented
Great! I'll get it merged in 🙂

2021-06-16 07:45 UTC, merged