Reference management models content v9
umbraco/UmbracoDocs pull request #3334
Opened 2021-07-13 12:45 UTC by erikjanwestendorp

Belongs to #3145

2021-07-13 21:18 UTC, busrasengul commented
Thank you @erikjanwestendorp
It looks great as always! We'll get this review on our next meeting!
#h5yr

2021-07-16 13:39 UTC, busrasengul requested changes

2021-07-16 13:39 UTC, busrasengul commented on Reference/Management/Models/Content-v9.md
> +meta-title: Content Model
```suggestion
meta.Title: "Content Model"
```

2021-07-16 13:39 UTC, busrasengul commented on Reference/Management/Models/Content-v9.md
> +meta.Description: The Content class represents a single item in the content tree, its values are fetched directly from the database, not from the cache.
```suggestion
meta.Description: "The Content class represents a single item in the content tree, its values are fetched directly from the database, not from the cache." 
```

2021-07-16 13:39 UTC, busrasengul commented on Reference/Management/Models/Content-v9.md
> +Constructor for creating a new Content object where the necessary parameters are the name of the Content, the parent of the Content as an `IContent` object, the ContentType as an `IContentType` objec
```suggestion
Constructor for creating a new Content object where the necessary parameters are the name of the Content, the parent of the Content as an `IContent` object, the ContentType as an `IContentType` object and a `PropertyCollection` for the Content being created. In addition, there is an optional parameter for the culture.
```

2021-07-16 13:40 UTC, erikjanwestendorp commented on Reference/Management/Models/Content-v9.md
> +Constructor for creating a new Content object where the necessary parameters are the name of the Content, the parent of the Content as an `IContent` object, the ContentType as an `IContentType` objec
@busrasengul Updated

2021-07-16 13:43 UTC, merged