Reference management models content type v9
umbraco/UmbracoDocs pull request #3340
Opened 2021-07-15 09:26 UTC by erikjanwestendorp

Belongs to #3145

2021-07-15 09:41 UTC, busrasengul commented
You're on fire @erikjanwestendorp 
We'll check this tomorrow 💪🏼

2021-07-16 13:33 UTC, busrasengul requested changes

2021-07-16 13:33 UTC, busrasengul commented on Reference/Management/Models/ContentType-v9.md
> +meta-title: ContentType Model
```suggestion
meta.Title: "ContentType Model"
```

2021-07-16 13:33 UTC, busrasengul commented on Reference/Management/Models/ContentType-v9.md
> +meta.Description: A ContentType corresponds to the Document Type found in the backoffice.
```suggestion
meta.Description: "A ContentType corresponds to the Document Type found in the backoffice."
```

2021-07-16 13:35 UTC, erikjanwestendorp commented on Reference/Management/Models/ContentType-v9.md
> +meta.Description: A ContentType corresponds to the Document Type found in the backoffice.
@busrasengul Updated 😄

2021-07-16 13:41 UTC, merged