Reference management models dictionary item
umbraco/UmbracoDocs pull request #3342
Opened 2021-07-15 09:47 UTC by erikjanwestendorp

Belongs to #3145

2021-07-15 10:04 UTC, busrasengul commented
Thanks a lot @erikjanwestendorp 
This one also made to the list of the PRs to review tomorrow too 😊

2021-07-16 13:29 UTC, busrasengul requested changes

2021-07-16 13:29 UTC, busrasengul commented on Reference/Management/Models/DictionaryItem-v9.md
> +meta-title: DictionaryItem Model
```suggestion
meta.Title: "DictionaryItem Model"
```

2021-07-16 13:29 UTC, busrasengul commented on Reference/Management/Models/DictionaryItem-v9.md
> +meta.Description: Represents a Dictionary Item. A Dictionary Item is what you see in the Translation / Dictionary tree.
```suggestion
meta.Description: "Represents a Dictionary Item. A Dictionary Item is what you see in the Translation / Dictionary tree."
```

2021-07-16 13:29 UTC, busrasengul commented on Reference/Management/Models/DictionaryItem-v9.md
> +Constructor for creating a new `DictionaryItem` object where the necessary parameters are the parentKey as `Guid` and the key of the `DictionaryItem` as a `string`. Use this one if you want to create
```suggestion
Constructor for creating a new `DictionaryItem` object where the necessary parameters are the parentKey as `Guid` and the key of the `DictionaryItem` as a `string`. Use this one if you want to create a `DictionaryItem` underneath another one.
```

2021-07-16 13:35 UTC, erikjanwestendorp commented on Reference/Management/Models/DictionaryItem-v9.md
> +Constructor for creating a new `DictionaryItem` object where the necessary parameters are the parentKey as `Guid` and the key of the `DictionaryItem` as a `string`. Use this one if you want to create
@busrasengul Updated 😄

2021-07-16 13:40 UTC, merged