Reference management models media
umbraco/UmbracoDocs pull request #3349
Opened 2021-07-15 16:35 UTC by erikjanwestendorp

Belongs to #3145 

Updated the parameter names in the constructors from contentType to mediaType, see also [PR ](https://github.com/umbraco/Umbraco-CMS/pull/10689)the CMS.

2021-07-16 13:25 UTC, busrasengul requested changes

2021-07-16 13:25 UTC, busrasengul commented on Reference/Management/Models/Media-v9.md
> +meta-title: Media Model
```suggestion
meta.Title: "Media Model"
```

2021-07-16 13:25 UTC, busrasengul commented on Reference/Management/Models/Media-v9.md
> +meta.Description: The Media class represents a single item in the media tree.
```suggestion
meta.Description: "The Media class represents a single item in the media tree."
```

2021-07-16 13:27 UTC, erikjanwestendorp commented on Reference/Management/Models/Media-v9.md
> +meta.Description: The Media class represents a single item in the media tree.
@busrasengul Updated 😄

2021-09-13 07:09 UTC, jonat123 commented
@erikjanwestendorp @busrasengul with the release of RC-3 last week, I'll go ahead and merge in this PR :D

2021-09-13 07:09 UTC, merged