Added an extra optionale step to the installation process
umbraco/UmbracoDocs pull request #3637
Opened 2021-11-12 09:55 UTC by JeffreyPerplex

When having a workshop yesterday at UmbracoDK Festival I could not install Umbraco v9 although I followed all the steps. Magician Sebastiaan helped me out and I wanted to make sure that his magic solution was included in the documentation as well

2021-11-15 14:51 UTC, busrasengul commented
Thank you @JeffreyPerplex 
This is great!! We'll review this soon :)

2021-11-19 10:52 UTC, marcemarc requested changes
@JeffreyPerplex thanks for sprinkling some of Seb's secret magic into the docs, we just had some suggestions to the wording, which we have specifically specified in this review.

2021-11-19 10:52 UTC, marcemarc commented on UmbracoNetCoreUpdates.md
> +If you are sure that you've installed the templates (see the previous step) but the command prompt keeps telling you that there is "No template found matching: Umbraco" it can help to specificy the s
```suggestion
If you are sure that you've installed the templates (see the previous step) but the command prompt keeps telling you that there is "No template found matching: Umbraco" then you can 'work around' by detailing the specific version in the `--nuget-source` option.
```

2021-11-19 10:52 UTC, marcemarc commented on UmbracoNetCoreUpdates.md
> +1. Use a command prompt of your choice to specify the specific sources. Please note that you can update the version (9.0.1.) to the latest version that is available.
```suggestion
```

2021-11-19 10:52 UTC, marcemarc commented on UmbracoNetCoreUpdates.md
> +    ```
```suggestion
    ```
Where 9.0.1 is replaced with the latest version that is available that you are trying to install.
```

2022-01-14 11:42 UTC, merged

2022-01-14 11:42 UTC, marcemarc commented
@JeffreyPerplex I has tweaked the text - but merged this in! thanking you!