New page set-up/Application settings
umbraco/UmbracoDocs pull request #3936
Opened 2022-04-25 13:01 UTC by sajumb

The text for the new feature

2022-04-25 13:59 UTC, eshanrnh requested changes
The PR looks good, @sajumb 💪 

I've added the Feature availability Note to the PR along with a couple of suggestions.

2022-04-25 13:59 UTC, eshanrnh commented on Umbraco-Cloud/Set-Up/Application-Settings/index.md
> +A change of an application setting enables you to change one specific behavoir of the app service that an environment is running in. The objective with application settings are to empower you with fe
```suggestion
A change of an application setting enables you to change one specific behavior of the app service that an environment is running in. The objective of application settings is to empower you with features or functionality that aren't available by default.
```

2022-04-25 13:59 UTC, eshanrnh commented on Umbraco-Cloud/Set-Up/Application-Settings/index.md
> +Currently the only setting that currently is available is the _enable client certificate loaded fromm file system_.
```suggestion
Currently, the only setting that is available is the _enable client certificate loaded from file system_.
```

2022-04-25 13:59 UTC, eshanrnh commented on Umbraco-Cloud/Set-Up/Application-Settings/index.md
> +If your cloud project needs to load a client certificate (such as a X.509 certificate) at runtime you can turn on this feature for one or more environments.
```suggestion
If your cloud project needs to load a client certificate (such as an X.509 certificate) at runtime you can turn on this feature for one or more environments.
```

2022-04-25 13:59 UTC, eshanrnh commented on Umbraco-Cloud/Set-Up/Application-Settings/index.md
> +By turning this feature on for an environment you will be able to load a client certificate as a file during run-time of your cloud project.
```suggestion
By turning this feature on for an environment, you will be able to load a client certificate as a file during the run-time of your cloud project.
```

2022-04-25 13:59 UTC, eshanrnh commented on Umbraco-Cloud/Set-Up/Application-Settings/index.md
> +You can find more information on loading a certificate from a file [here](https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate-in-code#load-certificate-from-file).
```suggestion
For more information on loading a certificate from a file, see the [Load certificate in Windows apps](https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate-in-code#load-certificate-from-file) section in the Microsoft documentation.
```

2022-04-25 13:59 UTC, eshanrnh commented on Umbraco-Cloud/Set-Up/Application-Settings/index.md
> +When toggling the setting you will be met by a confirmation prompt. An enabling/disabling of this feature will enforce a restart of the environment.
```suggestion
When toggling the setting, a confirmation prompt is displayed. Enabling/disabling this feature enforces a restart of the environment.
```

2022-04-26 06:38 UTC, sajumb commented on Umbraco-Cloud/Set-Up/Application-Settings/index.md
> +A change of an application setting enables you to change one specific behavoir of the app service that an environment is running in. The objective with application settings are to empower you with fe
Great suggestions. I accept! :-)

2022-04-26 06:38 UTC, sajumb commented on Umbraco-Cloud/Set-Up/Application-Settings/index.md
> +Currently the only setting that currently is available is the _enable client certificate loaded fromm file system_.
Great suggestions. I accept! :-)

2022-04-26 06:38 UTC, sajumb commented on Umbraco-Cloud/Set-Up/Application-Settings/index.md
> +If your cloud project needs to load a client certificate (such as a X.509 certificate) at runtime you can turn on this feature for one or more environments.
Is it really an X.509 and not a X.509?

2022-04-26 06:38 UTC, sajumb commented on Umbraco-Cloud/Set-Up/Application-Settings/index.md
> +By turning this feature on for an environment you will be able to load a client certificate as a file during run-time of your cloud project.
Great suggestions. I accept! :-)

2022-04-26 06:39 UTC, sajumb commented on Umbraco-Cloud/Set-Up/Application-Settings/index.md
> +You can find more information on loading a certificate from a file [here](https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate-in-code#load-certificate-from-file).
Great suggestions. I accept! :-)

2022-04-26 06:39 UTC, sajumb commented on Umbraco-Cloud/Set-Up/Application-Settings/index.md
> +versionFrom: 7.0.0
Great :-)

2022-04-26 06:39 UTC, sajumb commented on Umbraco-Cloud/Set-Up/Application-Settings/index.md
> +If your cloud project needs to load a client certificate (such as a X.509 certificate) at runtime you can turn on this feature for one or more environments.
But is to, I accept :-)

2022-04-26 09:54 UTC, eshanrnh commented
Looks good 💪 Merging it in 🙂

2022-04-26 09:55 UTC, merged