Add missing documentation about the UmbracoContext
umbraco/UmbracoDocs pull request #4013
Opened 2022-05-30 14:09 UTC by dampee

Not sure if I put in in the right folder. What do you think?

2022-05-31 07:49 UTC, sofietoft requested changes
Looks great @dampee !

And I think the placement of the doc is correct. Would it make sense to add a link to it from here as well: https://our.umbraco.com/documentation/Reference/Querying/ ?

I made a few suggestions as well.
Let me know if something doesn't make sense!

2022-05-31 07:49 UTC, sofietoft commented on Reference/Querying/UmbracoContext/index.md
> +You can use the UmbracoContext to access the content & media cache. Other useful properties are the the original & cleaned url's of the current request. And last, but not least, you can also check if
```suggestion
You can use UmbracoContext to access the content and media cache. Other useful properties are the original and cleaned URLs of the current request. You can also check if the current request is running in "preview" mode.
```

2022-05-31 07:49 UTC, sofietoft commented on Reference/Querying/UmbracoContext/index.md
> +If you are using Views or Partial View Macros you can reference UmbracoHelper with the syntax: `@UmbracoContext`
Shouldn't `UmbracoHelper` here be `UmbracoContext` instead? 🤔 

```suggestion
If you are using Views or Partial View Macros you can reference the UmbracoContext with the syntax: `@UmbracoContext`
```

2022-05-31 07:49 UTC, sofietoft commented on Reference/Querying/UmbracoContext/index.md
> +Example of getting `UmbracoContext` in a controller:
```suggestion
The following is an example of how to get access to the `UmbracoContext` in a controller:
```

2022-05-31 07:49 UTC, sofietoft commented on Reference/Querying/UmbracoContext/index.md
> +UmbracoContext is registered with a scoped lifetime (see [Microsoft documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0#lifetime-and-regi
```suggestion
UmbracoContext is registered with a scoped lifetime. See the [Microsoft documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0#lifetime-and-registration-options) for more information. A service scope is created for each request, which means you can resolve an instance directly in a controller.
```

2022-06-14 12:15 UTC, dampee commented
Accepted all your changes. They made sense indeed. Thanks for reviewing!

> And I think the placement of the doc is correct. Would it make sense to add a link to it from here as well: [https://our.umbraco.com](https://our.umbraco.com/documentation/Reference/Querying/)[/documentation/Reference/Querying/](https://our.umbraco.com/documentation/Reference/Querying/) ?

To me that makes sense indeed as you would use it in most lot of cases to query for content.

2022-07-07 09:19 UTC, merged