Update KeyVault article for v10
umbraco/UmbracoDocs pull request #4064
Opened 2022-06-03 13:25 UTC by erikjanwestendorp

Belongs to: https://github.com/umbraco/UmbracoDocs/issues/4039

2022-06-03 13:45 UTC, eshanrnh commented
Thanks for the PR, @erikjanwestendorp 👏 We will review this soon 🙂

2022-06-09 06:53 UTC, sofietoft requested changes
Looks great @erikjanwestendorp !
Thanks for verifying this for v10 👏 

I've made a few suggestions and added some comments.
Hope it all makes sense 🤞

2022-06-09 06:53 UTC, sofietoft commented on Extending/Key-Vault/index-v10.md
> +## Installing through command line
Looks to me like a subheading to the "Installing the package" section? I could be wrong though. What do you think?

```suggestion
### Installing through command line
```

2022-06-09 06:53 UTC, sofietoft commented on Extending/Key-Vault/index-v10.md
> +Navigate to your project folder, which is the folder that contains your .csproj file. Now use the following 'dotnet add package' command to install the package:
```suggestion
Navigate to your project folder, which is the folder that contains your `.csproj` file. Now use the following `dotnet add package` command to install the package:
```

2022-06-09 06:53 UTC, sofietoft commented on Extending/Key-Vault/index-v10.md
> +The next step is to add the Azure Key Vault endpoint to the 'appsettings.json' file.
```suggestion
The next step is to add the Azure Key Vault endpoint to the `appsettings.json` file. 
```

2022-06-09 06:53 UTC, sofietoft commented on Extending/Key-Vault/index-v10.md
> +After adding the Key Vault endpoint you have to update the `CreateHostBuilder` method which you can find in the `Program.cs` class.
I realize that it is a "class", but I think in the context here, it makes more sense to use "file", as it's a file you need to open and edit, right? 🤔 

```suggestion
After adding the Key Vault endpoint you have to update the `CreateHostBuilder` method which you can find in the `Program.cs` file. 
```

2022-06-09 06:53 UTC, sofietoft commented on Extending/Key-Vault/index-v10.md
> +There are several ways to access the Azure Key Vault. It is important that the user you are logging in with has access to the Key Vault. You can assign roles using the Azure Portal.
```suggestion
There are different ways to access the Azure Key Vault. It is important that the user you are logging in with has access to the Key Vault. You can assign roles using the Azure Portal. 
```

2022-06-09 07:05 UTC, erikjanwestendorp commented
@sofietoft Thanks for you review! 😄. 

I just updated the PR with the suggestions. I assume these changes should also be made for the v9 article?

2022-06-09 07:51 UTC, sofietoft commented
Yeah, that's a good point! 😅 
If the text is a one-to-one, then they should also be made on the other version.

You up for it? 😄 
Perhaps even add it to this one, so we can "smack two flies with one smack" (is that a danish saying? 🤔 😂 )!

2022-06-09 08:51 UTC, erikjanwestendorp commented
@sofietoft Yes the text is one-to-one there is only a small difference in the code.  Just updated the v9 article. 👍. 

And "smack two flies with one smack" is a dutch saying also! 🤣

2022-06-09 08:55 UTC, sofietoft approved these changes
This is great @erikjanwestendorp ! 🙌 

Thanks again for updating the articles.
I'll get merge it right in!

Hope to see you next week for Codegarden 🍻 🎉

2022-06-09 08:56 UTC, merged