Added article for v9 to v10 upgrade on Cloud
umbraco/UmbracoDocs pull request #4082
Opened 2022-06-08 11:10 UTC by eshanrnh

2022-06-08 13:35 UTC, sofietoft reviewed
Some initial notes: (just adding them now, as I might not finish the guide before heading home for today)

- No need to use the version number whenever referencing the project - "Umbraco 9". The 8 to 9 article used an approach with having 2 Cloud project. That's not the case this time, so I don't think it's necessary to reference Umbraco 9 anymore. Perhaps "just" call it "the project" instead.

2022-06-09 07:25 UTC, jonat123 commented on Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
> +* Create a backup of the database from your project, see the [Database backups](https://our.umbraco.com/documentation/umbraco-cloud/Databases/Backups/) article or clone down the project and take a ba
```suggestion
* Create a backup of the database from your project, see the [Database backups](https://our.umbraco.com/documentation/umbraco-cloud/Databases/Backups/) article or clone down the project and take a backup of the local Database (Make sure to restore the content from your cloud environment).
```
```suggestion
* Create a backup of the database from your project, see the [Database backups](https://our.umbraco.com/documentation/umbraco-cloud/Databases/Backups/) article or clone down the project and take a backup of the local Database (Ensure to restore the content from your cloud environment).
```

2022-06-09 07:25 UTC, jonat123 commented on Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
> +* Create a backup of the database from your project, see the [Database backups](https://our.umbraco.com/documentation/umbraco-cloud/Databases/Backups/) article or clone down the project and take a ba
```suggestion
* Create a backup of the database from your project, see the [Database backups](https://our.umbraco.com/documentation/umbraco-cloud/Databases/Backups/) article or clone down the project and take a backup of the local Database (Make sure to restore the content from your cloud environment).
```
```suggestion
* Create a backup of the database from your project, see the [Database backups](https://our.umbraco.com/documentation/umbraco-cloud/Databases/Backups/) article or clone down the project and take a backup of the local Database (Ensure to restore the content from your cloud environment).
```

2022-06-09 07:26 UTC, jonat123 commented
@eshanrnh Looks good to me :) 

I made one suggestion (Not sure why it decided to make two...) :)

2022-06-09 07:26 UTC, jonat123 commented
@eshanrnh Looks good to me :) 

I made one suggestion (Not sure why it decided to make two...) :)

2022-06-09 07:51 UTC, eshanrnh commented
> @eshanrnh Looks good to me :)
> 
> I made one suggestion (Not sure why it decided to make two...) :)

Github does the same with me too - 2 suggestions/comments (a little annoying at times) 😀

Incorporated the suggestion.

2022-06-09 08:21 UTC, sofietoft requested changes
I'm going to be running through the guide now.

I've made quite a few suggestion here - mainly it's cleaning up the list, so it always start with an action word, and only has a single action per item.
Let's try to make that our default 💪

2022-06-09 08:21 UTC, sofietoft commented on Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
> +* Clone down the **Development** environment from the Umbraco Cloud project, build and run the project locally and make sure to log in to the backoffice.
Should there also be a step for restoring content? I guess you would wanna test the upgrade against that, right?

```suggestion
* Clone down the **Development** environment from the Umbraco Cloud project.
* Build and run the project locally.
* Make sure to log in to the backoffice.
* Restore content from your Cloud enviroment.
```

2022-06-09 08:21 UTC, sofietoft commented on Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
> +## Step 1: Content Migration
```suggestion
## Step 1: Clone down your environment
```

2022-06-09 08:21 UTC, sofietoft commented on Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
> +* Create a backup of the database from your project, see the [Database backups](https://our.umbraco.com/documentation/umbraco-cloud/Databases/Backups/) article or clone down the project and take a ba
```suggestion
* Create a backup of the database
  * Directly from your environment. See the [Database backups](https://our.umbraco.com/documentation/umbraco-cloud/Databases/Backups/) article 
  * Or clone down and restore the project, and take a backup of the local Database.
```

2022-06-09 08:21 UTC, sofietoft commented on Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
> +* On the Cloud portal, go to the project that you wish to upgrade and navigate to **Settings** -> **Advanced**. Scroll down to **Runtime Settings** section and **Enable .NET 6 for your Umbraco 9 inst
```suggestion
* Go to the project in the Cloud portal.
* Navigate to **Settings** -> **Advanced**
* Scroll down to the **Runtime Settings** section.
* **Enable .NET 6 for your Umbraco 9 install** for each environment of your Cloud project.
```

2022-06-09 08:21 UTC, sofietoft commented on Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
> +* Right-click your project solution in the **Solution Explorer** and select **Properties**.
```suggestion
* Right-click your project solution in the **Solution Explorer**.
* Select **Properties**.
```

2022-06-09 08:21 UTC, sofietoft commented on Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
> +* In the **General** section of the **Application** tab, select **.Net 6.0** from the **Target Framework** drop-down.
```suggestion
* Select **.Net 6.0** from the **Target Framework** drop-down in the **General** section of the **Application** tab.
```

2022-06-09 08:21 UTC, sofietoft commented on Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
> +* In the **NuGet Package manager Solution**, go to the **Installed** tab and choose **Umbraco.Cms**.
```suggestion
* Go to the **Installed** tab In the **NuGet Package manager Solution**.
* Choose **Umbraco.Cms**
```

2022-06-09 08:21 UTC, sofietoft commented on Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
> +* Select your project, choose **10.0.0** from the **Version** drop-down and click **Install** to upgrade your project to version 10.
```suggestion
* Select your project.
* Choose **10.0.0** from the **Version** drop-down.
Click **Install** to upgrade your project to version 10.
```

2022-06-09 08:21 UTC, sofietoft commented on Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
> +* Similarly, update the below packages referenced in your project to the latest versions available on NuGet either through the **NuGet Package Manager** or **Package Manager Console (PowerShell)**:
```suggestion
* Update the below packages referenced in your project to the latest versions available on NuGet either through the **NuGet Package Manager** or **Package Manager Console (PowerShell)**:
```

2022-06-09 08:21 UTC, sofietoft commented on Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
> +* To re-enable the appsettings IntelliSense, update your schema reference in the **appsettings.json**, **appsettings.Development.json**, **appsettings.Production.json**, and **appsettings.Staging.jso
```suggestion
* Re-enable the appsettings IntelliSense by updating your schema reference in the **appsettings.json**, **appsettings.Development.json**, **appsettings.Production.json**, and **appsettings.Staging.json** files from:
```

2022-06-09 08:21 UTC, sofietoft commented on Umbraco-Cloud/Upgrades/Migrating-from-9-to-10/index.md
> +* Remove the following files and folders *manually* from your local project and on the cloud **Development** environment through [KUDU](../../Set-Up/Power-Tools/index.md) both from the `repository` a
This is a long item.
Would it make sense to split it in two?
One for local, and one for KUDU?

2022-06-10 12:45 UTC, merged