Changes for v10
umbraco/UmbracoDocs pull request #4142
Opened 2022-06-24 10:53 UTC by ault

Middleware is no longer necessary... see: https://github.com/umbraco/Umbraco.StorageProviders/releases

2022-06-24 12:25 UTC, eshanrnh commented
Thanks for the PR, @ault 💪 We will review this soon 🙂

2022-06-24 12:51 UTC, ronaldbarendse requested changes
The Umbraco.StorageProviders package for v10 indeed doesn't require custom middleware anymore, so we should either create a separate page for v9/v10 or add a note.

2022-06-24 12:51 UTC, ronaldbarendse commented on Extending/FileSystemProviders/Azure-Blob-Storage/index.md
> -Next invoke `UseAzureBlobMediaFileSystem();` in the `.WithMiddleware` call, like so:
This article targets both v9 and v10, so instead of removing all code, we should add a note saying this is not required in v10 anymore.

2022-06-30 10:53 UTC, sofietoft commented
Hi all 👋 

It seems that there was already an approved PR for updating this article: #4113.
As that PR adds a separate version for v10, we decided to go with that instead.

Thanks again for contributing and helping us keeping the docs up to date 💪

2022-06-30 10:53 UTC, closed without merging