New article: 2-factor authentication on Cloud
umbraco/UmbracoDocs pull request #4365
Opened 2022-09-09 09:02 UTC by jonat123

Added a new article for 2-factor authentication on Umbraco Cloud.

2022-09-09 09:15 UTC, Fjellvang reviewed
Maybe we have to be carefull with the QR code in Auth-app.png ?

I think its good to replace that same screenshot with a enrollement picture from a dummyaccount or dev etc?

2022-09-09 09:16 UTC, jonat123 commented on Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/index.md
> +On Umbraco Cloud, you can add 2-factor authentication for your Umbraco Cloud account using either email, phone or a authenticator app when logging in to the Umbraco Cloud Portal.
```suggestion
On Umbraco Cloud, you can add 2-factor authentication for your Umbraco Cloud account using either email, phone, or an authenticator app when logging in to the Umbraco Cloud Portal.
```

2022-09-09 09:16 UTC, jonat123 commented on Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/index.md
> +## Enabeling 2-factor authentication
```suggestion
## Enabling 2-factor authentication
```

2022-09-09 09:17 UTC, jonat123 commented on Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/index.md
> +With email authentication you will get an email with a code that you need to enter when you log in to the Umbraco Cloud portal.
```suggestion
With email authentication, you will get an email with a code that you need to enter when you log in to the Umbraco Cloud portal.
```

2022-09-09 09:17 UTC, jonat123 commented on Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/index.md
> +You can use the Microsoft authenticator app for both iOS and android or any other authenticator app of your choice.
```suggestion
With the authenticator app, you need to use an authenticator app when you log in to the Umbraco Cloud Portal.

You can use the Microsoft Authenticator app for both iOS and android or any other authenticator app of your choice.
```

2022-09-09 09:17 UTC, jonat123 commented on Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/index.md
> +With the phone authenticator, when you log in to the Umbraco Cloud portal, you can choose to either receive a SMS with a code to enter when login in or a call to log you in.
```suggestion
With the phone authenticator, when you log in to the Umbraco Cloud portal, you can choose to either receive an SMS with a code to enter when login in or a call to log you in.
```

2022-09-09 09:18 UTC, sitereactor commented
I think it looks good, but maybe end this article with a "Logging in with 2FA" section where you explain/highlight what the login flow will look like with 2FA in place. And just use one of the MFA methods as an example.
Then we'll have both the enrollment and login parts covered.

2022-09-09 09:19 UTC, jonat123 commented
@Fjellvang that makes total sense, i did not think about it when taking the images 😅

I'll make sure that the QR code is just a dummy one that does not work!

2022-09-09 09:19 UTC, Fjellvang requested changes

2022-09-09 09:19 UTC, Fjellvang commented on Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/index.md
> +![Authenticator app](images/auth-app.png)
as mentioned in comment, ensure the image is not a valid QR code for your production account

2022-09-12 07:26 UTC, sofietoft reviewed
Article looks great @jonat123 ! 💪 

I've made a few comments here and there.
Let me know what you think!

2022-09-12 07:26 UTC, sofietoft commented on Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/index.md
> +2-factor authentication can be enabled when editing your Umbraco Cloud profile
```suggestion
2-factor authentication can be enabled when editing your Umbraco Cloud profile.
```

2022-09-12 07:26 UTC, sofietoft commented on Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/index.md
> +4. Follow the steps shown to enable 2-factor authentication.
```suggestion
1. Go to your profile on Umbraco Cloud.
2. Choose **Edit Profile** in the Profile Settings section.
3. Choose the desired 2-factor authentication.
4. Follow the steps shown to enable 2-factor authentication.
```

2022-09-12 07:26 UTC, sofietoft commented on Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/index.md
> +With the authenticator app, you need to use an authenticator app when you log in to the Umbraco Cloud Portal.
```suggestion
You have the option to use an Authenticator App when logging in to the Umbraco Cloud Portal.
```

2022-09-12 07:26 UTC, sofietoft commented on Umbraco-Cloud/Set-Up/2-factor-authentication-on-cloud/index.md
> +You can use the Microsoft Authenticator app for both iOS and android or any other authenticator app of your choice.
```suggestion
You can use the Microsoft Authenticator App for both iOS and Android or any other authenticator app of your choice.
```

2022-09-12 12:10 UTC, jonat123 commented
Thanks for the reviews!

The QR code has been replaced with one that just leads back to our.umbraco.com instead :) 

@sitereactor I think it is fine to just show how to enable the 2-factor authentication, and not more than that, once it is enabled I think the steps are pretty clear in what is shown on the Umbraco Cloud portal :)

2022-09-12 12:10 UTC, jonat123 commented
I am merging this in now :D

2022-09-12 12:10 UTC, merged

2022-09-12 12:11 UTC, sitereactor commented
Alright 👍