Created guide to migrate users to Umbraco Cloud
umbraco/UmbracoDocs pull request #4428
Opened 2022-10-04 11:55 UTC by jonat123

2022-10-04 12:06 UTC, jonat123 commented on Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md
> +Umbraco Identity (Umbraco ID) is the single sign-on (SSO) feature across all Umbraco Cloud services.
```suggestion
Umbraco Identity (Umbraco ID) is the Single Sign-On (SSO) feature across all Umbraco Cloud services.
```

2022-10-05 08:02 UTC, eshanrnh requested changes
Looks good, @jonat123 🙌 Just a couple of suggestions.

2022-10-05 08:02 UTC, eshanrnh commented on Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/Migrating-Users-To-Umbraco-Cloud/index.md
> +Once the script has been run on your Umbraco Cloud Database it is now time for the users to login to the Cloud backoffice.
```suggestion
Once the script has been run on your Umbraco Cloud Database, it is time for the users to log in to the Cloud backoffice.
```

2022-10-05 08:02 UTC, eshanrnh commented on Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/Migrating-Users-To-Umbraco-Cloud/index.md
> +The user will be promted to login, they should use the password from the on-premise installation.
```suggestion
The user will be prompted to log in and they should use the password from the on-premises installation.
```

2022-10-05 08:02 UTC, eshanrnh commented on Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/Migrating-Users-To-Umbraco-Cloud/index.md
> +Once the user has been verified they will be redirected to the backoffice and their user has been migrated to Umbraco ID.
```suggestion
Once the user has been verified, they will be redirected to the backoffice and their user has been migrated to Umbraco ID.
```

2022-10-05 08:02 UTC, eshanrnh commented on Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md
> +It is required to access any project pages as well as backoffices.
```suggestion
It is required to access any project pages as well as the backoffice.
```

2022-10-05 08:02 UTC, eshanrnh commented on Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/index.md
> +To migrate the users from your on-premise site to Umbraco Cloud and Umbraco ID follow the [Migrate Users to Cloud guide](/Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/Migrating-Users-To-Umbrac
```suggestion
To migrate the users from your on-premises site to Umbraco Cloud and Umbraco ID, follow the [Migrate Users to Cloud guide](/Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/Migrating-Users-To-Umbraco-Cloud/index.md) article.
```

2022-10-06 07:35 UTC, eshanrnh approved these changes
Looks good, @jonat123 🙌 Merging it in.

2022-10-06 07:37 UTC, merged