Clarified the requirements
umbraco/UmbracoDocs pull request #4438
Opened 2022-10-09 16:04 UTC by RyuLindow

2022-10-10 07:48 UTC, sofietoft requested changes
Thanks for updating the requirements here @RyuLindow ! 💪 

I've made a few comments - please take a look.
Also, consider whether it makes sense to have these details in the list. A list usually lists steps in a guide or a list of things required for something. What you've added here, is more extra information to the first item on the list - right? 🤔

2022-10-10 07:48 UTC, sofietoft commented on Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps.md
> +* You will need to setup 2 x App service plans with 1 x web app in each - one for the backoffice (Administrative) environment and another for your scalable public-facing environment (Public)
```suggestion
* You will need to setup 2 x App service plans with 1 x web app in each - one for the backoffice (Administrative) environment and another for your scalable public-facing environment (Public).
```

2022-10-10 07:48 UTC, sofietoft commented on Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps.md
> +* This'll allow for for proper scaling of the (Administrative) and the (Public) web apps.
```suggestion
* This will allow for the proper scaling of the Administrative and Public web apps.
```

2022-10-10 07:48 UTC, sofietoft commented on Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps.md
> +* The app service plan with the (Public) web app can be scaled both out and up and having multiple instanced of it is the exact conctept of load balancing.
```suggestion
* The App Service plan with the Administrative web app should only be scaled up. The reason for this is that the web app needs to stay as a single instance.
* The App Service plan with the Public web app can be scaled both out and up.
```

2022-10-10 13:25 UTC, RyuLindow commented
We can add a note at the bottom if you want. Otherwise, I think it looks good :)

2022-10-11 06:36 UTC, sofietoft commented on Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps.md
>  * You will need 1 x SQL server that is shared with these 2 web apps
OK. I think we can make this even better and easier to read:

```suggestion
* 2 x App service plans with 1 x web app in each:
  * One for the backoffice (Administrative) environment and another and
  * One for your scalable public-facing environment (Public).
* 1 x SQL server that is shared with these 2 web apps

The setup above will allow for the proper scaling of the Administrative and Public web apps.

The App Service plan with the Administrative web app should only be scaled up. The reason for this is that the web app needs to stay as a single instance.

The App Service plan with the Public web app can be scaled both out and up.

```

2022-10-12 07:44 UTC, sofietoft commented
Looks great @RyuLindow ! 💪 

Thanks a bunch for help improving this article!
Let's get it merged in.

2022-10-12 07:45 UTC, merged