Instructions for restoring a bacpac file
umbraco/UmbracoDocs pull request #4483
Opened 2022-10-17 23:05 UTC by CarlSargunar

This is an amend to the documentation, with thanks to Seb for his help. It outlines the steps required to restore a bacpac file from an Umbraco Cloud backup to a local SQL Server instance

2022-10-17 23:07 UTC, CarlSargunar commented
This fixes issue  #4484

2022-10-17 23:09 UTC, CarlSargunar commented
Note - on the failing check, the database IS called master, that's an unfortunate historical artefact of SQL server

2022-10-18 06:35 UTC, sofietoft reviewed
Thanks for the PR @CarlSargunar ! 💪 

This is a great addition to the article!
I'll make sure we have the process reviewed as soon as possible.
Also, I made a few suggestions - mainly to grammar and stuff!

2022-10-18 06:35 UTC, sofietoft commented on Umbraco-Cloud/Databases/Backups/index.md
> +## Restoring a cloud backup to a SQL Server Database
```suggestion
## Restoring a Cloud backup to a SQL Server Database
```

2022-10-18 06:35 UTC, sofietoft commented on Umbraco-Cloud/Databases/Backups/index.md
> +In order to restore a .bacpac file to a SQL Server database, you will need to first ensure that the SQL Server has has 'Contained Database Authentication' enabled. This is a security feature that is
```suggestion
To restore a `.bacpac` file to a SQL Server database, you need to ensure that the SQL Server has **Contained Database Authentication** enabled. This is a security feature that is disabled by default. Without enabling it you will not be able to restore the database. For reference, check out the [Microsoft documentation on the topic](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/contained-database-authentication-server-configuration-option?view=sql-server-ver16).
```

2022-10-18 06:35 UTC, sofietoft commented on Umbraco-Cloud/Databases/Backups/index.md
> +To Enable Contained Database Authentication, run the following SQL against your sql server on the Master database
```suggestion
To Enable Contained Database Authentication, run the following SQL against your SQL server on the Master database.
```

2022-10-18 06:35 UTC, sofietoft commented on Umbraco-Cloud/Databases/Backups/index.md
> +- Connect to your SQL Server using Sql Server Management Studio (SSMS).
```suggestion
- Connect to your SQL Server using SQL Server Management Studio (SSMS).
```

2022-10-18 06:35 UTC, sofietoft commented on Umbraco-Cloud/Databases/Backups/index.md
> +- Expand "Databases", right-click "Databases", select "Tasks", then select "Import Data-tier Application...".
```suggestion
- Expand "Databases" and right-click "Databases".
- Select "Tasks" and then "Import Data-tier Application...".
```

2022-10-18 06:35 UTC, sofietoft commented on Umbraco-Cloud/Databases/Backups/index.md
> +- Proceed through the dialog, by browsing to the saved location of your bacpac file, and then setting the options appropriate to your coniguration
```suggestion
- Proceed through the dialog, by browsing to the saved location of your `.bacpac` file.
- Set the options appropriate to your configuration.
```

2022-10-18 07:32 UTC, jonat123 reviewed
@CarlSargunar Thanks for the PR.

I have been testing it out, however, I have had no issues restoring a backup of a cloud site to my local instance with both a database for a v8 site and a database for v10.

On my end, it works just fine without Enableling Contained Database Authentication.

Just to outline what I did:

- I created a project with some content on the cloud (on both v8 and 10)

- I connected to my DB and created a backup by following the docs

- Then I connect to my local instance of SSMS and click on databases and import data-tier application

- I run through the wizard

- And it restores it successfully

Is there something that I am missing?

It seems to me that it should work without enabling the Contained Database Authentication.

2022-10-18 08:03 UTC, CarlSargunar commented
@jonat123 it depends if you already had that configuration enabled on your server. Depending on how you have installed SQL Server, and depending on what edition you install that may not be enabled. For example - I normally run a minimal SQL Server through Docker to keep the footprint low, where it was not installed. However if you run the full Dev edition of SQL server locally then that setting may have already been enabled. 

The problem is it's not obvious what the problem is when you try and restore a database. Perhaps the wording should be changed so that we say "If you have a problem, then this is what you need to do". 

For reference, I had a bug which I raised which illustrates the error

https://our.umbraco.com/forum/using-umbraco-and-getting-started//110228-export-bacpac-and-import-into-sql-server

2022-10-18 08:20 UTC, jonat123 commented
@CarlSargunar Thanks for elaborating  👍

Makes sense to me, as you say the wording should be changed a bit, what do you say to something like this:

> You might need to enable Contained Database Authentication before being able to restore your Umbraco Cloud Database locally.
> 
> 
> To enable it, run the following SQL query against your SQL server on the Master database:
> 
> sp_configure 'contained database authentication', 1;  
> GO  
> RECONFIGURE;  
> GO  

I also think it would make sense if the above is in a note as well :)

2022-10-18 08:28 UTC, CarlSargunar commented
cool - I'll do that update in a bit :-)

2022-10-18 10:17 UTC, CarlSargunar commented
Updated wording as discussed @jonat123

2022-10-18 10:56 UTC, jonat123 commented on Umbraco-Cloud/Databases/Backups/index.md
> +When you restore a bacpac to your SQL server if it fails, check that you have the configuration flag for 'Contained Database Authentication' set to true. If this is not set the import will fail.
```suggestion
When restoring a bacpac to your SQL server if it fails, check that you have the configuration flag for 'Contained Database Authentication' set to true. 

If it is not set the import will fail.
```

2022-10-18 10:57 UTC, jonat123 commented on Umbraco-Cloud/Databases/Backups/index.md
> +For refrence please see [this article](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/contained-database-authentication-server-configuration-option?view=sql-server-ver16).
```suggestion
For reference please see the [contained database authentication documentation](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/contained-database-authentication-server-configuration-option?view=sql-server-ver16).
```

2022-10-18 11:00 UTC, jonat123 requested changes
Great, looks good to me @CarlSargunar :) 

Just made a couple of suggestions as it was complaining about the length of the sentence :) 

Also, make sure to have a look at the suggestions from Sofie as well 😄

Once they have been approved we can merge in the PR 😁

2022-10-18 11:16 UTC, CarlSargunar commented
Darned sentence length :-)

No worries. I re-structured the PR so @sofietoft I think your suggestions were on the old structure, if you want any more tweaks now please let me know. I've taken any amends which I could take

2022-10-18 11:44 UTC, jonat123 commented on Umbraco-Cloud/Databases/Backups/index.md
> +When restoring a bacpac to your SQL server if it fails, check that you have the configuration flag for 'Contained Database Authentication' set to true.
```suggestion
When restoring a `bacpac` to your SQL server if it fails, check that you have the configuration flag for 'Contained Database Authentication' set to true. 
```

2022-10-18 11:44 UTC, jonat123 commented on Umbraco-Cloud/Databases/Backups/index.md
> +- Proceed through the dialog, by browsing to the saved location of your bacpac file, and then setting the options appropriate to your coniguration
```suggestion
- Proceed through the dialog, by browsing to the saved location of your `bacpac` file, and then setting the options appropriate to your configuration
```

2022-10-18 11:46 UTC, jonat123 commented on Umbraco-Cloud/Databases/Backups/index.md
> +For reference please see the [contained database authentication Server Configuration Option documentation](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/contained-database-a
```suggestion
For reference please see the [Microsoft documentation on the topic](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/contained-database-authentication-server-configuration-option?view=sql-server-ver16).
```

2022-10-18 11:49 UTC, jonat123 commented
@CarlSargunar Great!

Just read it over one last time and noticed a couple of things and made a couple of suggestions 😄

Once they have been committed I will merge the PR 😁

2022-10-18 11:54 UTC, CarlSargunar commented
Wow - I read it too, but totally missed that - shows how much we automatically correct. Thanks for that

2022-10-18 12:01 UTC, jonat123 commented
@CarlSargunar hehe :D 

Anyways great addition to the documentation :D 

Thanks for the PR, I will merge it in :D

2022-10-18 12:01 UTC, merged