adding v10 specific information for integration testing
umbraco/UmbracoDocs pull request #4503
Opened 2022-10-21 13:58 UTC by Mantus667

Adding v10 specific information on how to setup a project, state the bug in the pre 10.3.1 version of the test package and giving a sample on how to setup appsettings.Tests.json and GlobalSetup

2022-10-24 08:40 UTC, sofietoft commented
Thanks for the PR @Mantus667 ! 💪 

I see there are some warnings about long sentences in both articles.. Would you be up for taking a shot at resolving those? 🤞 
Then I'll run it by our developers for a check mean while 😄

2022-10-24 14:32 UTC, Mantus667 commented
Hi @sofietoft ,
will have a look if I can shorten/restructure the sentences ab bit. :)

2022-10-27 11:52 UTC, Zeegaan commented
Hi @Mantus667, did you get the `UmbracoTestServerTestBase` tests working locally? 🤔 
When trying to follow your steps, I get errors about the `.deps.json` file not existing :(

2022-11-29 06:55 UTC, Zeegaan requested changes
Got it to work, had a few comments 👍

2022-11-29 06:55 UTC, Zeegaan commented on Implementation/Integration-Testing/index.md
> +        var url = PrepareUrl<BackOfficeAssetsController>(x=>x.GetSupportedLocales());
We need to use the `PrepareApiControllerUrl` instead 👍 
```suggestion
        var url = PrepareApiControllerUrl<BackOfficeAssetsController>(x => x.GetSupportedLocales());
```

2022-11-29 06:55 UTC, Zeegaan commented on Implementation/Integration-Testing/index.md
> +
```suggestion
In this example you have to note three things:

- You still need the `CustomGlobalSetupTeardown` class
- The PrepareUrl to get the URL of an Action and ensure all services use the URL information when requested. 
- The Client which is a normal HttpClient, but the base URL points to the test server that is set up for each test.

Note that you can still use GetRequiredService to get the services required to seed data.

```

2022-12-06 10:41 UTC, sofietoft commented
Hi all 👋 

I took the liberty to add @Zeegaan s suggestions to this PR.

I'll have to close it though, as it's possible to merge this directly with the docs since the migration to the new platform. I've migrated the PR: https://github.com/umbraco/UmbracoDocs/pull/4721
I apologize for the inconvenience @Mantus667 !
I promise that your PR will still count towards the Umbraco Hacktoberfest challenge 🙌 

Thanks again for helping to update this article!

2022-12-06 10:41 UTC, closed without merging