Update Requirements article for Umbraco 11
umbraco/UmbracoDocs pull request #4525
Opened 2022-10-25 10:56 UTC by sofietoft

Updated
- .NET version to **7.0**
- Link to Microsoft documentation (line 56)

Are there any updated requirements in terms of local development or SQL?

2022-10-27 17:41 UTC, Jeavon commented on Fundamentals/Setup/Requirements/index-v11.md
> +  * Microsoft Windows 7 SP1, 8.1, 10 and 11
I don't believe Windows 7 or 8.1 are supported by .NET7 - https://github.com/dotnet/announcements/issues/226

2022-10-27 17:54 UTC, Jeavon commented on Fundamentals/Setup/Requirements/index-v11.md
> +  * [Microsoft Visual Studio](https://www.visualstudio.com/) 2022
v17.4 minimum is required for .net7 RC2 - currently, this is available only on preview edition

2022-11-14 06:18 UTC, Zeegaan requested changes
Had a few things besides the two points @Jeavon brings up 👍

2022-11-14 06:18 UTC, Zeegaan commented on Fundamentals/Setup/Requirements/index-v11.md
> +  * [JetBrains Rider](https://www.jetbrains.com/rider) **version 2020.3 and higher**
This should be 2022.3 👍

2022-11-14 06:18 UTC, Zeegaan commented on Fundamentals/Setup/Requirements/index-v11.md
> +* SQL Server 2012 and higher
```suggestion
* SQL Server 2012 and higher / SQLite 3.38.0 or higher
```

2022-11-14 10:10 UTC, Zeegaan approved these changes
After the changes it looks good to me 🎉

2022-11-14 10:12 UTC, sofietoft commented
Thanks @Zeegaan and @Jeavon !

I'll merge this one in then 👏

2022-11-14 10:12 UTC, merged

2022-11-14 10:13 UTC, Jeavon commented
All good!