Feature/umbraco hackathon docs vscode
umbraco/UmbracoDocs pull request #5020
Opened 2023-03-09 15:32 UTC by jacksorjacksor

Here are my first few suggestions for the documentation change - there are a few more I want to make but I need to get better at using Umbraco first!!

2023-03-10 07:41 UTC, sofietoft requested changes
Thanks a bunch for the PR @jacksorjacksor 💪 

I've made a couple of suggestions - let me know what you think!

2023-03-10 07:41 UTC, sofietoft commented on 11/umbraco-cms/SUMMARY.md
> +    * [Install using Visual Studio Code](fundamentals/setup/install/install-umbraco-with-vs-code.md)
You need to also update the title of the article, when updating the link to it in the navigation 💪 
They are tied together, so if you don't do it, GitBook will change this back to use the article title again 😅

2023-03-10 07:41 UTC, sofietoft commented on generic/contribute/getting-started.md
> +## IDE / Text Editor
Perhaps instead we could call this "Writing docs locally" or something?

2023-03-10 07:41 UTC, sofietoft commented on generic/contribute/getting-started.md
> +We recommend using Visual Studio Code for making changes to the documentation.
Added a littel more context to this sentence. Let me know what you think!

```suggestion
We recommend using a tool like Visual Studio Code for making changes to the documentation on your local machine.
```

2023-03-10 08:39 UTC, sofietoft reviewed
Thanks for considering the suggestions @jacksorjacksor !

I see there are a couple of warnings - one for a too-long sentence, and one for an acronym.
Would you be up for taking a shot at resolving those?
You can learn more about the guidelines here: https://docs.umbraco.com/welcome/contribute/style-guide

2023-03-10 08:41 UTC, jacksorjacksor commented
100% - will look into after/during Umbraco Spark!

Sent from Proton Mail for iOS

On Fri, Mar 10, 2023 at 08:39, sofietoft ***@***.***> wrote:

> @sofietoft commented on this pull request.
>
> Thanks for considering the suggestions ***@***.***(https://github.com/jacksorjacksor) !
>
> I see there are a couple of warnings - one for a too-long sentence, and one for an acronym.
> Would you be up for taking a shot at resolving those?
> You can learn more about the guidelines here: https://docs.umbraco.com/welcome/contribute/style-guide
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/umbraco/UmbracoDocs/pull/5020#pullrequestreview-1334374768), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/ABMRMNABFL47GUXMK5FR4EDW3LSEPANCNFSM6AAAAAAVVITEKM).
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-03-14 07:50 UTC, sofietoft commented
Thanks @jacksorjacksor !

I'll make sure this is merged in 💪

2023-03-14 07:50 UTC, merged

2023-03-14 09:33 UTC, jacksorjacksor commented
YAY - thank you @sofietoft !!