Release notes for Forms/Deploy 12
umbraco/UmbracoDocs pull request #5180
Opened 2023-05-17 13:01 UTC by AndyButland

Includes:

- Documented breaking changes from removing obsolete code constructs for Forms 12
- Documented breaking changes from removing obsolete code constructs for Deploy 12

Can be reviewed and go live any time on or after May 24th.

2023-05-19 06:53 UTC, jonat123 commented on 12/umbraco-deploy/upgrades/version-specific.md
> +Version 11 of Umbraco Deploy has a minimum dependency on Umbraco CMS core of `12.0.0`. It runs on .NET 7.
```suggestion
Version 12 of Umbraco Deploy has a minimum dependency on Umbraco CMS core of `12.0.0`. It runs on .NET 7.
```

2023-05-19 06:53 UTC, jonat123 commented on 12/umbraco-deploy/upgrades/version-specific.md
> +Version 11 contains a number of breaking changes. We don't expect many projects to be affected by them as they are in areas that are not typical extension points.  For reference though, the full deta
```suggestion
Version 12 contains a number of breaking changes. We don't expect many projects to be affected by them as they are in areas that are not typical extension points.  For reference though, the full details are listed here:
```

2023-05-19 06:54 UTC, jonat123 commented on 12/umbraco-forms/installation/version-specific.md
> +Version 11 contains a number of breaking changes. If you do run into any, they should be straightforward to adjust and recompile.
```suggestion
Version 12 contains a number of breaking changes. If you do run into any, they should be straightforward to adjust and recompile.
```

2023-05-19 06:56 UTC, jonat123 requested changes
@AndyButland Looks good!

Only noticed that there were a few times in the v12 parts it said v11, I have made suggestions for them :D 

Once fixed I'll make sure it is merged in on the 24th.

2023-05-22 07:59 UTC, AndyButland commented
Yes, 23rd please if that's OK.  There was some confusion on the date but we're looking to get these out tomorrow.

2023-05-22 11:59 UTC, jonat123 commented
@AndyButland As the space is not live yet(Meaning if you don't have access to gitbook, you can't see it yet) I will merge this PR in.

Then we will make sure that it is all public tomorrow with the release of the RC :)

2023-05-22 11:59 UTC, merged