Add 'Use File Scoped Namespaces'
umbraco/UmbracoDocs pull request #5318
Opened 2023-07-24 10:16 UTC by erikjanwestendorp

## Description

Add 'Use File Scoped Namespaces' to the code-samples article in the cotribute folder as suggested in https://github.com/umbraco/UmbracoDocs/issues/5260#issuecomment-1647487697

This PR belongs to https://github.com/umbraco/UmbracoDocs/issues/5260

## Type of suggestion

* [x] Update contribution guidelines

2023-07-25 08:21 UTC, sofietoft requested changes
Thanks for the PR @erikjanwestendorp ! 💪 

Looks great! I've added a single comment - take a look when you have a sec.

2023-07-25 08:21 UTC, sofietoft commented on generic/contribute/code-samples.md
> +The use of file scoped namespaces improves, among other things, the readability of the code samples. Therefore, use file scoped namespaces in the examples. See below how to use file scoped namespaces
Just a few small adjustments:

```suggestion
The use of file-scoped namespaces improves, among other things, the readability of the code samples. Therefore, use file scoped namespaces in the examples. See below how to use file-scoped namespaces:
```

2023-07-26 07:09 UTC, erikjanwestendorp commented
@sofietoft Thanks for your review, I just updated the PR with your suggestion.

2023-07-26 10:21 UTC, sofietoft commented
Thanks @erikjanwestendorp ! 💪 

I'll get this merged!

2023-07-26 10:21 UTC, merged