Delivery API: Add section about deeply nested JSON
umbraco/UmbracoDocs pull request #5325
Opened 2023-07-28 08:29 UTC by kjac

## Description

I have added a section about how to handle deeply nested JSON, if this is produced by the Delivery API as a consequence of deeply nested content structures.

My editor seems to have performed some clean-up of trailing white-spaces throughout the article. I guess this is based on the `.editorconfig` of this repo... might as well include those changes now rather than later 😄 

Cross-linking the origin for future reference: https://github.com/umbraco/Umbraco-CMS/issues/14610

## Type of suggestion

* [x] New content

## Product & version (if relevant)

v12

## Deadline (if relevant)

Not relevant.

2023-07-31 09:06 UTC, sofietoft reviewed
Thanks for the PR @kjac ! 💪 

I've added a couple of comments.

Also, regarding the formatting happening between lines 431 and 475 - I think we need to run those by @elit0451 . I seem to remember she had some issues with this when she initially wrote the article. It's a GitBook vs. GitHub thing.

2023-07-31 09:06 UTC, sofietoft commented on 12/umbraco-cms/reference/content-delivery-api/README.md
> +.NET imposes a limit on the depth of object nesting within rendered JSON. This is done in an effort to detect cyclic references (read more [here](https://learn.microsoft.com/en-us/dotnet/api/system.t
```suggestion
.NET imposes a limit on the depth of object nesting within rendered JSON. This is done in an effort to detect cyclic references. Learn more about it in [the official .NET API docs](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.maxdepth)).

If the limit is exceeded, .NET will throw a `JsonException`.
```

2023-07-31 09:06 UTC, sofietoft commented on 12/umbraco-cms/reference/content-delivery-api/README.md
> +First we have to add these `using` statements to `Startup.cs`:.
```suggestion
First, we have to add these `using` statements to `Startup.cs`:
```

2023-08-10 09:33 UTC, alina-tincas requested changes
Hi @kjac 👋 

I have a few suggestions to the changes you have made and was wondering if you can take a look at them and let me know your thoughts on them? 😊

2023-08-10 09:33 UTC, alina-tincas commented on 12/umbraco-cms/reference/content-delivery-api/README.md
> +.NET imposes a limit on the depth of object nesting within rendered JSON. This is done in an effort to detect cyclic references. Learn more about it in [the official .NET API docs](https://learn.micr
seems there is an extra ")" at the end 😄 
```suggestion
.NET imposes a limit on the depth of object nesting within rendered JSON. This is done in an effort to detect cyclic references. Learn more about it in [the official .NET API docs](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.maxdepth).
```

2023-08-10 09:52 UTC, kjac commented
Good stuff @alina-tincas ❤️ 

I've got to run some formatting past Elitsa on this one before it can be merged, so please don't merge it in just yet... I'll get back to you here.

2023-08-10 10:34 UTC, alina-tincas commented
No worries, and sure thing 🙌

2023-08-14 10:11 UTC, jonat123 commented
@kjac great! 

As Alina is on vacation, i will merge in the PR :D

2023-08-14 10:11 UTC, jonat123 approved these changes

2023-08-14 10:11 UTC, merged