Document existence of 'ShowDomainWarnings' setting
umbraco/UmbracoDocs pull request #5334
Opened 2023-08-04 16:03 UTC by marcemarc

## Description

We added a new Content Setting in V11/v12 called ShowDomainWarnings, by default this is true, but can be set to false to turn off the warnings if they become annoying.

umbraco/Umbraco-CMS#13954

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

V11 and V12

## Deadline (if relevant)

can be now

2023-08-09 07:45 UTC, alina-tincas requested changes
Hi @marcemarc thank you for this PR 🙌 

I have a few suggestions so I was wondering if you can take a look at them and do the same change for the v12 docs? 😊

2023-08-09 07:45 UTC, alina-tincas commented on 11/umbraco-cms/reference/configuration/contentsettings.md
> +If you have a multilingual Umbraco site and you haven't configured Domains correctly for each language then every time you publish you will get the following warning: "Content published: Domains are
When writing documentation we have a style guide to follow so the documentation is more readable. One of the guides is to make the [sentences shorter than 25 words](https://docs.umbraco.com/welcome/contribute/style-guide#long-sentences), therefore I am suggesting the following: 
```suggestion
If you do not configure Domains for each language in a multilingual site then every time you publish your content you get this warning:

`Content published: Domains are not configured for multilingual site, please contact an administrator, see log for more information.`

If you have a use case for not setting the domains, you can set this setting **ShowDomainWarnings** to `false` to stop the warning from displaying.
```

2023-08-21 09:25 UTC, alina-tincas commented
Hi @marcemarc 👋 I was wondering if you have seen my previous suggestions and if you would be up to making the mentioned changes? Otherwise please let me know if you are not able to so then we can put this in our backlog 👍

2023-08-21 17:24 UTC, marcemarc commented
Hi  @alina-tincas 

I have been on my hols! so I did indeed miss your feedback, all updated and for both branches, I think correctly! Let me know if not and I'll tweak further.

Thanking you!

Marc

2023-08-28 07:39 UTC, alina-tincas commented
Hi @marcemarc thank you for making these changes and no worries 🙌 

All looks good now, so am merging this in 💪

2023-08-28 07:39 UTC, merged