Added documentation for the new FileStreamSecurityValidator
umbraco/UmbracoDocs pull request #5344
Opened 2023-08-10 11:16 UTC by Migaroez

Documentation for
https://github.com/umbraco/Umbraco-CMS/pull/14657

2023-08-11 09:08 UTC, alina-tincas requested changes
Hi @Migaroez 👋 

Thank you for the PR! 🙌 

In order for the pages to show up in the documentation navigation, can you please add the reference to those pages in the[ SUMMARY.md ](https://docs.umbraco.com/welcome/contribute/pull-request#step-1-creating-a-fork) as well? 😁 

Also, once you would like these changes merged in, please let us know 👍

2023-08-11 09:08 UTC, alina-tincas commented on 10/umbraco-cms/reference/security/serverside-file-validation.md
> +```
as it is csharp it makes the format to match it 😁 
```suggestion
```csharp
```

2023-08-21 09:27 UTC, alina-tincas commented
Hi @Migaroez 👋 
I was wondering if you have seen my previous suggestions and if you are able to make the mentioned changes?

Also, please let me know once all those changes should be merged in 👍

2023-09-06 09:09 UTC, Migaroez commented
Versions to add to this docs

[12.2.0-rc](https://www.nuget.org/packages/Umbraco.Cms/12.2.0-rc) - Since September 7th - 2023
[11.5.0](https://www.nuget.org/packages/Umbraco.Cms/11.5.0) - Since September 7th - 2023
[10.7.0](https://www.nuget.org/packages/Umbraco.Cms/10.7.0) - Since September 7th - 2023
[8.18.9](https://www.nuget.org/packages/UmbracoCms/8.18.9) - Since August 28th - 2023
[7.15.11](https://www.nuget.org/packages/UmbracoCms/7.15.11) - Since September 5th - 2023

2023-09-25 11:09 UTC, merged