Ambertvu/localizations
umbraco/UmbracoDocs pull request #5399
Opened 2023-09-07 14:33 UTC by Ambertvu

## Description

I've clarified the introduction of the language file page. I noticed that some had a tough time finding the correct syntax and explanation on how to get and create the files. I hope that by first giving a short explanation and clearly describing the `key` and `area` elements it will be easier to pickup.

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [x] Other

2023-09-13 08:45 UTC, alina-tincas requested changes
Hi @Ambertvu, thank you for the PR 🙌 

An example with clarification is indeed nice to have! I will just run this over by our developers to confirm the example, and meanwhile I have made a suggestions to replace the community link with https://community.umbraco.com/. Let me know what you think about the suggestion 😊

2023-09-13 10:45 UTC, Ambertvu commented
Done and done, thanks!

2023-09-25 10:43 UTC, bergmania approved these changes

2023-09-25 11:17 UTC, alina-tincas requested changes
Hi @Ambertvu thank you for your patience! The code examples look good.

I have just one suggestion, can you take a look at it and let me know what you think? 😊

2023-09-25 11:17 UTC, alina-tincas commented on 10/umbraco-cms/extending/language-files.md
> +- Add translations for your packages [see here for docs on how to include translations for your own package](packages/language-files-for-packages.md)
To make the link text shorter and hence readable that it is a link:
```suggestion
-  Read [Add translations for your packages](packages/language-files-for-packages.md) article to see how to include translations for your own package.
```

2023-09-25 11:17 UTC, alina-tincas commented on 11/umbraco-cms/extending/language-files.md
> +- Add translations for your packages [see here for docs on how to include translations for your own package](packages/language-files-for-packages.md)
```suggestion
-  Read [Add translations for your packages](packages/language-files-for-packages.md) article to see how to include translations for your own package.
```

2023-09-25 11:17 UTC, alina-tincas commented on 12/umbraco-cms/extending/language-files.md
> +- Add translations for your packages [see here for docs on how to include translations for your own package](packages/language-files-for-packages.md)
```suggestion
-  Read [Add translations for your packages](packages/language-files-for-packages.md) article to see how to include translations for your own package.
```

2023-09-25 14:00 UTC, Ambertvu commented
@alina-tincas I did a small change to your suggestion (not sure how to do it on github, so I just approved and changed them)

I removed the 'article' word.

I think it's reads better with:
'Read the xxxx article to see how..`
or this felt even better:
'Read xxxx to see how..`

and not
`Read xxx article to see how..`

2023-09-26 08:33 UTC, alina-tincas commented
That is all right @Ambertvu 😊 

Merging it in, thank you again for the PR 🙌

2023-09-26 08:36 UTC, merged

2023-09-26 08:40 UTC, alina-tincas commented
(as for making changes, you can do them locally on the same branch you have pushed those changes to, or you can just commit the suggestions directly in github)

2023-09-26 08:52 UTC, Ambertvu commented
Anytime!

Yea that's what I did, hah, thought maybe there was an other way. Thanks!