Add documentation for protected content in the Delivery API
umbraco/UmbracoDocs pull request #5410
Opened 2023-09-13 10:09 UTC by kjac

## Description

Added docs for the upcoming "protected content" feature in the Delivery API. The feature is slated for V12.3.

⚠️ Do NOT merge this in until V12.3RC is out ⚠️ 

## Type of suggestion

* [ ] Typo/grammar fix
* [x] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

V12.3

## Deadline (if relevant)

V12.3RC is out on October 19, so it would be nice for this to go out then too.

2023-09-13 11:09 UTC, elit0451 approved these changes
Great docs! 💪

2023-09-13 11:19 UTC, kjac commented on 12/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api.md
> +Remember to use `umbraco-member` as `client_id` when authorizing. `client_secret` can be omitted, as it is not used by the authorization flow.
Let's do that. 👍 will amend

2023-09-13 15:13 UTC, alina-tincas requested changes
Hi @kjac thank you for the PR 🙌 

Awesome to see it has been approved by @elit0451 as well :h5YR

I have just a few suggestions, can you please take a look at them and let me know what you think? 😊 

Then I will make sure it is merged in on on October 19 💪

2023-09-13 15:13 UTC, alina-tincas commented on 12/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api.md
> +For more inspiration on using the built-in member authentication, visit [this tutorial](https://docs.umbraco.com/umbraco-cms/tutorials/members-registration-and-login). Here you will also learn how to
```suggestion
For more inspiration on using the built-in member authentication, check the [Members Registration and Login](https://docs.umbraco.com/umbraco-cms/tutorials/members-registration-and-login) article. Here you will also learn how to create member sign-up functionality.
```

2023-09-13 15:13 UTC, alina-tincas commented on 12/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api.md
> +Now we can test the setup. Again we'll be calling `https://{server-host}/umbraco/delivery/api/v1/security/member/authorize` as described previously, but we need to add one more query string parameter
Again and previously seem to be the in the same sentence 🤔 
```suggestion
Now we can test the setup. We'll be calling `https://{server-host}/umbraco/delivery/api/v1/security/member/authorize` as described previously, but we need to add one more query string parameter:
```

2023-09-14 06:07 UTC, kjac commented on 12/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api.md
> +To put these samples into context, please refer to the article above.
It's all the previous sections of this article. We have opted to move the samples to the very end of the article, to keep the flow as clear as possible. Does that make sense?

2023-09-14 07:20 UTC, alina-tincas commented on 12/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api.md
> +To put these samples into context, please refer to the article above.
ah I see now! Then all is good 👍

2023-10-19 06:51 UTC, alina-tincas approved these changes

2023-10-19 06:52 UTC, merged