Swagger is no longer a limitation in the Delivery API - it's a feature
umbraco/UmbracoDocs pull request #5413
Opened 2023-09-13 11:17 UTC by kjac

## Description

Moved the Swagger section from "Limitations" to the "Endpoints" part of the article. The Swagger docs are no longer limited, they should be treated as a feature 😄 

## Type of suggestion

* [ ] Typo/grammar fix
* [x] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

V12

## Deadline (if relevant)

Not relevant. As soon as possible, but absolutely no rush 😆

2023-09-13 11:22 UTC, elit0451 approved these changes
🙌 🙌

2023-09-13 14:37 UTC, alina-tincas requested changes
Hi @kjac thank you for the PR 🙌 

I have just one suggestion, can you please take a look at it? 😊

2023-09-13 14:37 UTC, alina-tincas commented on 12/umbraco-cms/reference/content-delivery-api/README.md
> +All endpoints are documented in a Swagger document at `{yourdomain}/umbraco/swagger`. Keep in mind that this document is not available in production mode by default (see also [this article](https://d
When sharing a link it should be described 😁 
```suggestion
All endpoints are documented in a Swagger document at `{yourdomain}/umbraco/swagger`. Keep in mind that this document is not available in production mode by default. For more information check the [API versioning and OpenAPI](https://docs.umbraco.com/umbraco-cms/reference/api-versioning-and-openapi) article.
```

2023-09-14 06:55 UTC, kjac commented
Good stuff @alina-tincas 👍

2023-09-14 07:08 UTC, alina-tincas commented
Looks good now so am merging it in 😁

2023-09-14 07:08 UTC, merged