New backoffice: Fix a few glitches in the dashboard tutorial
umbraco/UmbracoDocs pull request #5446
Opened 2023-09-21 13:28 UTC by kjac

## Description

The multi-part dashboard tutorial for the new backoffice has a few glitches and errors. While these are somewhat simple to fix, they do pose an unnecessary barrier to get started.

While I was there, I also opted to use "part" instead of "session" when referring to the different parts of the tutorial, and cleaned up a few wordings.

## Type of suggestion

* [ ] Typo/grammar fix
* [x] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

V14

## Deadline (if relevant)

Not relevant 😄

2023-09-22 08:53 UTC, jonat123 commented on new-backoffice/tutorials/creating-a-custom-dashboard.md
> +The guide is divided into several parts. In this first part will go through:
```suggestion
The guide is divided into four parts. The first part will go through the following:
```

2023-09-22 08:55 UTC, jonat123 requested changes
@kjac Looks really good!

Just made a small suggestion to fix the only vale warning :-)

2023-09-25 05:31 UTC, kjac commented
Thanks @jonat123 - all ready to go then 😄

2023-09-25 06:55 UTC, jonat123 approved these changes
@kjac Awesome!

Looks good :-) 

Will merge in :D

2023-09-25 06:55 UTC, merged