Block Grid Editor is available from v10.4
umbraco/UmbracoDocs pull request #5459
Opened 2023-09-27 20:52 UTC by snerpton

## Description

Updated documentation to reflect Block Grid was introduced to v10 in 10.4. Current documentation suggests only the Block List Block Editor is available in v10.

See the following links about the introduction of Block Grid into v10:

- https://umbraco.com/blog/umbraco-103-release-candidate/
- https://our.umbraco.com/download/releases/1040

## Type of suggestion

* [x] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

Documentation of v10.

## Deadline (if relevant)

It is not time-critical, but it is important to maintain v10 documentation as this version has LTS.

2023-09-28 12:56 UTC, alina-tincas requested changes
HI @snerpton 👋 

Thank you for the PR! I have a re-phrasing suggestion, can you please take a look at it and let me know what you think? 😊

2023-09-28 12:56 UTC, alina-tincas commented on 10/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/README.md
> +Umbraco 10 initially shipped with one Block Editor, Block List, with Block Grid introduced in Umbraco 10.4.
```suggestion
Umbraco 10 initially shipped with one Block Editor which is Block List. Block Grid editor has been introduced from version 10.4.0.
```

2023-10-04 21:15 UTC, snerpton commented on 10/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/README.md
> +Umbraco 10 initially shipped with one Block Editor, Block List, with Block Grid introduced in Umbraco 10.4.
Hi @alina-tincas works for me :-)

2023-10-06 06:48 UTC, alina-tincas commented
Awesome, merging it in 😊 

Thank you again for the PR 🙌

2023-10-06 06:49 UTC, alina-tincas approved these changes

2023-10-06 06:50 UTC, merged