Update extending umbraco-element - The new backoffice
umbraco/UmbracoDocs pull request #5652
Opened 2023-11-23 13:27 UTC by erikjanwestendorp

## Description

Update extending umbraco-element:

- [x] Remove easily

## Type of suggestion

* [x] Styleguide

## Product & version (if relevant)
The new backoffice

2023-11-23 14:07 UTC, jonat123 commented on new-backoffice/extending/umbraco-element/README.md
> +This provides a few methods to connect with Backoffice, giving you the ability to:
```suggestion
This provides a few methods to connect with the Backoffice, giving you the ability to:
```

2023-11-23 14:08 UTC, jonat123 requested changes
@erikjanwestendorp Looks good, just one minor thing to just make the sentence sound better 😄

2023-11-23 14:10 UTC, erikjanwestendorp commented
@jonat123 Thanks! Just updated the PR with your suggestion.  😄

2023-11-24 08:40 UTC, jonat123 approved these changes

2023-11-24 08:40 UTC, merged