Add docs for Delivery API range query feature in V13
umbraco/UmbracoDocs pull request #5682
Opened 2023-12-05 09:33 UTC by kjac

## Description

Added docs for the new Delivery API range query feature in V13.

Note that the "Filter operators" section from https://github.com/umbraco/UmbracoDocs/pull/5592 has not been included in the V13 docs yet. Since this feature requires changes to said section, I have included it in this PR 😄 

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

V13.0

## Deadline (if relevant)

Ideally on December 14 when V13.0 is out 😄 but if it's a few days later that's fine too. This is not a major feature.

2023-12-05 13:41 UTC, alina-tincas requested changes
small change

2023-12-06 13:10 UTC, elit0451 requested changes
The content is great, I've just added a few comments

2023-12-06 13:10 UTC, elit0451 commented on 13/umbraco-cms/reference/content-delivery-api/extension-api-for-querying.md
> +The range operators (the latter four) only work with number and date fields - `FieldType.Number` and `FieldType.Date` respectively.
```suggestion
The range operators (_the latter four_) only work with number and date fields - `FieldType.Number` and `FieldType.Date` respectively.
```

2023-12-06 13:10 UTC, elit0451 commented on 13/umbraco-cms/reference/content-delivery-api/extension-api-for-querying.md
> +`GET /umbraco/delivery/api/v2/content?filter=customTagFilter:tag1,tag2`
Let's use the <code>```http</code> format as the other examples:

```suggestion
```http
GET /umbraco/delivery/api/v2/content?filter=customTagFilter:tag1,tag2
```
```

2023-12-06 13:10 UTC, elit0451 commented on 13/umbraco-cms/reference/content-delivery-api/extension-api-for-querying.md
> +`GET /umbraco/delivery/api/v2/content?filter=customTagFilter:tag1&filter=customTagFilter:tag2`
Same here:

```http
GET /umbraco/delivery/api/v2/content?filter=customTagFilter:tag1&filter=customTagFilter:tag2
```

2023-12-06 14:01 UTC, elit0451 approved these changes
Changes look great!

2023-12-13 11:55 UTC, jonat123 commented
@kjac Will merge this PR in so it is part of the v13 documentation tomorrow when we go live with it 😄

2023-12-13 11:55 UTC, merged