Update debugging
umbraco/UmbracoDocs pull request #5700
Opened 2023-12-11 13:46 UTC by erikjanwestendorp

## Description

Update debugging:
- [x] Change 'aka' to 'also known as'

## Type of suggestion

* [x] Styleguide

## Product & version (if relevant)
Umbraco CMS v10, 12 & 13

2023-12-11 15:43 UTC, alina-tincas requested changes
Hi @erikjanwestendorp thank you for the PR as always 😊 🙌 

I have one suggestion, can you please take a look into it and make the changes to all versions if you agree with it? 💡

2023-12-11 15:43 UTC, alina-tincas commented on 10/umbraco-cms/reference/debugging.md
> +* How far can you `F11` also knonw as `Step Into` and go down the rabbit hole of the Umbraco CMS source code?
```suggestion
* How far can you `F11`, also known as `Step Into`, and go down the rabbit hole of the Umbraco CMS source code?
```

2023-12-11 15:45 UTC, erikjanwestendorp commented on 10/umbraco-cms/reference/debugging.md
> +* How far can you `F11` also knonw as `Step Into` and go down the rabbit hole of the Umbraco CMS source code?
oops 😅

2023-12-11 15:48 UTC, erikjanwestendorp commented
@alina-tincas Oops... 😅, just updated the PR 😄

2023-12-12 08:01 UTC, alina-tincas approved these changes

2023-12-12 08:05 UTC, alina-tincas commented
No worries 🙈 

All looks good now, so this PR will be merged in Thursday😊

2023-12-18 08:39 UTC, merged