Update installdefaultdatasettings
umbraco/UmbracoDocs pull request #5705
Opened 2023-12-13 12:40 UTC by erikjanwestendorp

## Description

Update installdefaultdatasettings: 

- [x] change 'data type' to 'Data Type'

## Type of suggestion

* [x] Styleguide

## Product & version (if relevant)
Umbraco CMS v10, 12 & 13

2023-12-18 08:49 UTC, alina-tincas requested changes
Hi @erikjanwestendorp thank you for the PR 😊 

I have just few suggestions, can you please look into them and let me know what you think? 
(and if you agree with them, please make the changes to the other versions as well 💪 )

2023-12-18 08:49 UTC, alina-tincas commented on 10/umbraco-cms/reference/configuration/installdefaultdatasettings.md
> +For example, if different languages are set up in Umbraco, it's better not to recreate the default language (en-US). In other situations, certain Umbraco default Data, Member and Media Types may not
as it mentions in the original sentence it mentions that if "a different set of languages **from** Umbraco's default (en-US) have been set up":
```suggestion
For example, if different languages are set up in Umbraco, it's better not to recreate them from the default language (en-US). In other situations, certain Umbraco default Data, Member and Media Types may not be required.
```

2023-12-18 08:49 UTC, alina-tincas commented on 10/umbraco-cms/reference/configuration/installdefaultdatasettings.md
> +When working in a team and using Umbraco Deploy for schema updates, consider the colleague's local project setup. The default data may not always be useful.
```suggestion
When working in a team and using Umbraco Deploy for schema updates, consider your colleague's local project setup. The default installed data may not always be useful.
```

2023-12-18 13:28 UTC, erikjanwestendorp commented
@alina-tincas Thanks for your suggestions. Just updated the PR 😄

2023-12-21 07:47 UTC, alina-tincas approved these changes

2023-12-21 07:48 UTC, merged