Update release-notes.md for Stripe Payment provider v13.1.0
umbraco/UmbracoDocs pull request #5739
Opened 2023-12-28 07:37 UTC by umbracotrd

## Description

_What did you add/update/change?_

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [x] Updates related to a new version
* [ ] Other

## Product & version (if relevant)
It's a minor release so no rush on this.

## Deadline (if relevant)

_When should the content be published?_

2023-12-28 14:32 UTC, alina-tincas requested changes
Hi @umbracotrd thank you for the PR! 😃 

Can you please add the github link to the release note as well? 😊

2023-12-28 14:32 UTC, alina-tincas commented on commerce-add-ons/payment-providers/stripe/release-notes.md
> +#### 13.1.0 (December 28th 2023)
can you please add a link to this as well, similar to https://github.com/umbraco/UmbracoDocs/pull/5737/files? 😊 
![image](https://github.com/umbraco/UmbracoDocs/assets/83591955/f018eafb-92ed-4a8a-bc51-3423ac6494b0)

2024-01-04 07:53 UTC, alina-tincas commented on commerce-add-ons/payment-providers/stripe/release-notes.md
> +#### 13.1.0 (December 28th 2023)
Hi @umbracotrd I was wondering if you have seen my latest message and if you are able to make add the label for stripe and add a link to it here?  😊

2024-01-10 14:19 UTC, alina-tincas commented
Hi @umbracotrd Happy New Year 😊 

I was wondering if you have seen my latest message and if you are able to make the necessary changes?

2024-01-11 05:24 UTC, umbracotrd commented
Hi @alina-tincas, I've just added a label and link it to the release notes.

2024-01-11 08:54 UTC, alina-tincas approved these changes

2024-01-11 08:55 UTC, alina-tincas commented
Awesome, thank you for making the changes #h5YR 

Merging this in 😊

2024-01-11 08:55 UTC, merged