Update package manifest and property editor docs
umbraco/UmbracoDocs pull request #5795
Opened 2024-01-22 14:28 UTC by alina-tincas

## Description

_What did you add/update/change?_
Update package manifest and property editor docs as they were outdated from v8:
- https://docs.umbraco.com/umbraco-cms/extending/property-editors/package-manifest 
- https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-property-editor - also tested until step 2. There might be some code that is obsolete in step 3 and 4 but with v14 where angular is not used anymore these tutorial might need to be revisited and re-tested
## Type of suggestion

* [ ] Typo/grammar fix
* [x] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)
CMS 10, 12, 13

## Deadline (if relevant)

_When should the content be published?_
anytime

2024-01-24 09:53 UTC, jonat123 commented on 10/umbraco-cms/extending/property-editors/package-manifest.md
> +From version 9.2 some additional root elements was added, the purpose of these are to control and facilitate telemetry about the package, none of these are mandatory. The properties are:
```suggestion
From version 9.2 additional root elements were added, the purpose of these is to control and facilitate telemetry about the package, none of these are mandatory. The properties are:
```

2024-01-24 09:59 UTC, jonat123 commented on 10/umbraco-cms/tutorials/creating-a-property-editor/README.md
> +This guide explains how to set up a property editor, hook it into Umbraco's Data Types, AngularJS modules, and its injector, and finally how we can test our property editor.
```suggestion
This guide explains how to set up a property editor and hook it into Umbraco's Data Types, AngularJS modules, and injector. Finally, it explains how we can test our property editor.
```

2024-01-24 10:03 UTC, jonat123 commented on 10/umbraco-cms/tutorials/creating-a-property-editor/README.md
> +By the end of this tutorial, we will have a "suggestions" data type running inside of Umbraco, registered as a Data Type in the backoffice, and assigned to a Document Type. The data type can create a
```suggestion
By the end of this tutorial, we will have a "suggestions" data type running inside of Umbraco. It is registered as a Data Type in the backoffice, and assigned to a Document Type. The data type can create and suggest values.
```

2024-01-24 10:08 UTC, jonat123 requested changes
@alina-tincas Looks good :) 

I have made some suggestions to fix the vale errors :)

Please make sure they are added to all the versions 😄

2024-01-24 10:29 UTC, eshanrnh reviewed
Looks good to me. Couple of suggestions though 🙂

2024-01-26 09:35 UTC, eshanrnh commented on 10/umbraco-cms/extending/property-editors/package-manifest.md
> +namespace MyProject
using Umbraco.Cms.Core.Composing;

2024-01-29 11:58 UTC, alina-tincas commented on 10/umbraco-cms/extending/property-editors/package-manifest.md
> +            "alias": "Suggestions",
not necessarily. It works with both small and big first letter.

2024-01-29 12:08 UTC, alina-tincas commented on 10/umbraco-cms/extending/property-editors/package-manifest.md
> +namespace MyProject
there are 2 more using statements apart from composing, I will add them as well

2024-01-29 12:24 UTC, alina-tincas commented
Thank you both for the feedback 💪 I have made the changes as per your feedback, so I will merge this in 😊

2024-01-29 12:24 UTC, merged