Update workflow types
umbraco/UmbracoDocs pull request #5806
Opened 2024-01-25 13:32 UTC by erikjanwestendorp

## Description

Update workflow types:

* [x] Remove 'several'
* [x] Remove 'just'
* [x] Write shorter sentences

## Type of suggestion

* [x] Styleguide

## Product & version (if relevant)
Umbraco Forms

2024-01-30 08:20 UTC, alina-tincas requested changes
Hi @erikjanwestendorp thank you for the PR 🙌 

I have just one suggestion and can you please make the same changes to v10 and 12 as well? 😊

2024-01-30 08:20 UTC, alina-tincas commented on 13/umbraco-forms/editor/attaching-workflows/workflow-types.md
> +The endpoint extracts form fields and values using GET for querystrings and POST for form collections.
```suggestion
The receiving endpoint extracts form fields and values using GET for querystrings and POST for form collections.
```

2024-01-30 14:46 UTC, erikjanwestendorp commented
@alina-tincas Thanks for the review! 😄 Just updated the PR with your suggestion and updated v10 & 12.

2024-01-31 09:03 UTC, alina-tincas approved these changes

2024-01-31 09:04 UTC, alina-tincas commented
Awesome, thank you for making the changes 😁 Merging this in!

2024-01-31 09:04 UTC, merged