Update Modelsbuilder HasValue check
umbraco/UmbracoDocs pull request #5810
Opened 2024-01-29 09:21 UTC by marcemarc

## Description

_What did you add/update/change?_

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [x] Other

## Product & version (if relevant)

v13

## Deadline (if relevant)

whenever

---

The example was sending the 'value' of ModelEmail instead of the alias of the field...

... there is also a counterargument to say that HasValue shouldn't be being used here at all, in either with and without Modelsbuilder...

that instead we should be promoting

```
@if (!string.IsNullOrWhiteSpace(Model.Value<string>("email")))
```
and
```
@if (!string.IsNullOrWhiteSpace(Model.Email))
```

because HasValue isn't necessarily considering PropertyValueConverters...

2024-01-31 08:29 UTC, alina-tincas commented
Hi @marcemarc thank you for this PR! That is quite a good point! 

To keep it consistent with the other articles such as the label: https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/label#mvc-view-example I would suggest in this case to change the email address article like in the label article with:

**Without Modelsbuilder**
```
@if (Model.HasValue("email")){
        <p>@(Model.Value("email"))</p>
    }
```

**With Modelsbuilder**
```
@if (!string.IsNullOrEmpty(Model.Email))
    {
        <p>@Model.Email</p>
    }
```

Can you let me know what you think of the above and if you are up for the making the changes also for v12 and v10? 😊

2024-01-31 08:36 UTC, alina-tincas commented on 13/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/email-address.md
> +@if (Model.HasValue((nameof(Model.Email))
```suggestion
@if (Model.HasValue((nameof(Model.Email))))
```

2024-01-31 08:37 UTC, alina-tincas requested changes
missing 2 extra **))**

2024-02-09 14:22 UTC, alina-tincas commented
Hi @marcemarc I was wondering if you have seen my latest message to update the example with:

With Modelsbuilder

```
@if (!string.IsNullOrEmpty(Model.Email))
    {
        <p>@Model.Email</p>
    }
```

to fit with the other examples? The one you have added is a bit different than the rest from our documentation and if this examples is changed to your suggestions then the other examples will need to be changed with your suggestions as well. This is th reason why I am suggestions what can be seen above, as I can see it is used in other examples on our documentation such as: https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/label#mvc-view-example 

Also, can you please let me know if you are up for making the same change to version 12 and 10 of CMS as well to keep all docs versions consistent? 😊

2024-02-09 14:53 UTC, marcemarc commented
Hi @alina-tincas so many tabs open!, have found this one... yes, I have updated to match other examples of modelsbuilder hasvalue check throughout the site, I shall hunt down v12 and v10 pages!

2024-02-09 16:49 UTC, marcemarc commented
Hi @alina-tincas ok done, I think!

2024-02-13 08:47 UTC, alina-tincas approved these changes

2024-02-13 08:49 UTC, alina-tincas commented
Hehe, no worries @marcemarc! Thank you for making the changes 🙌 

All looks good now so am merging this in 😊 Thank you again for contributing to our documentation #h5YR

2024-02-13 08:51 UTC, merged