Update testing-stripe-webhooks-locally.md
umbraco/UmbracoDocs pull request #5815
Opened 2024-01-29 16:33 UTC by MMasey

## Description

This PR adds an additional way to test the Stipe Payment Provider locally, using the Stripe CLI. I found when using the ngrok approach, i would get errors due to the Umbraco Commerce Checkout package redirecting to the default domain, rather than the ngrok domain. 

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)
Umbraco Commerce - Stripe Payment Provider

2024-01-31 08:47 UTC, alina-tincas commented
Hi @MMasey, thank you for the PR 🙌 

We will take a look at the PR as soon as we can! 😊

2024-02-05 15:06 UTC, eshanrnh requested changes
The PR looks good, @MMasey 💪 Added couple of styling and doc guidelines suugestions.

2024-02-07 07:57 UTC, umbracotrd commented on commerce-add-ons/payment-providers/stripe/how-to-guides/testing-stripe-webhooks-locally.md
> +stripe listen --forward-to https:localhost:44321/umbraco/commerce/payment/callback/stripe-checkout/7fb00000-0000-0000-0000-000019094a7a/
should be `https://`

2024-02-07 08:10 UTC, umbracotrd commented on commerce-add-ons/payment-providers/stripe/how-to-guides/testing-stripe-webhooks-locally.md
> +stripe listen --forward-to https:localhost:44321/umbraco/commerce/payment/callback/stripe-checkout/7fb00000-0000-0000-0000-000019094a7a/
Should add a reminder about go to backoffice > Stripe payment method setting and updating webhook signing secret 
![image](https://github.com/umbraco/UmbracoDocs/assets/145000730/d9efdb3e-152b-44f4-864c-9f71848701fa)

2024-02-07 08:11 UTC, umbracotrd commented on commerce-add-ons/payment-providers/stripe/how-to-guides/testing-stripe-webhooks-locally.md
> +stripe listen --forward-to https:localhost:44321/umbraco/commerce/payment/callback/stripe-checkout/7fb00000-0000-0000-0000-000019094a7a/
@eshanrnh: The rest looks good to me.

2024-02-08 21:47 UTC, MMasey commented
Thanks @eshanrnh & @umbracotrd, I've committed those suggestions and added that additional step regarding the webhook signing secret too. 😄

2024-02-09 12:43 UTC, eshanrnh commented on commerce-add-ons/payment-providers/stripe/how-to-guides/testing-stripe-webhooks-locally.md
> +While running the site locally, make a note of your local store domain. For example: `https:localhost:44321`. Using the Stripe CLI, you can configure Stripe to forward any events to that URL.
```suggestion
While running the site locally, make a note of your local store domain. For example: `https://localhost:44321`. Using the Stripe CLI, you can configure Stripe to forward any events to that URL.
```

2024-02-09 12:44 UTC, eshanrnh commented on commerce-add-ons/payment-providers/stripe/how-to-guides/testing-stripe-webhooks-locally.md
> +stripe listen --forward-to https:localhost:44321/umbraco/commerce/payment/callback/stripe-checkout/7fb00000-0000-0000-0000-000019094a7a/
```suggestion
stripe listen --forward-to https://localhost:44321/umbraco/commerce/payment/callback/stripe-checkout/7fb00000-0000-0000-0000-000019094a7a/
```

2024-02-09 12:45 UTC, eshanrnh approved these changes
Looks good, @MMasey 🙌

2024-02-09 12:48 UTC, merged