Simplify DNS records section
umbraco/UmbracoDocs pull request #5826
Opened 2024-02-02 09:03 UTC by pijemcolu

## Description

The suggestions to not use A records was because they weren't static. Now that they are static we can simplify the docs and let the customers use their preferred record sets.

## Type of suggestion

* [ ] Typo/grammar fix
* [xx] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

Umbraco Cloud

## Deadline (if relevant)

n/a

2024-02-05 09:59 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/manage-hostnames/README.md
> +If you are using the [Former A and AAAA records](./#former-a-and-aaaa-records) consider changing them to the new A & AAAA records above as they will not become obsolete.
```suggestion
If you're using the [Former A and AAAA records](./#former-a-and-aaaa-records) consider changing them to the A & AAAA records above as they will not become obsolete.
```

2024-02-05 10:00 UTC, jonat123 requested changes
@pijemcolu Looks good :D 

I have added a small suggestion.

2024-02-05 10:00 UTC, pijemcolu commented
> @pijemcolu Looks good :D
> 
> I have added a small suggestion.

This is now confusing: ```If you are using the [Former A and AAAA records](./#former-a-and-aaaa-records) consider changing them to the new A & AAAA records above as they will not become obsolete.```

We should clear up which records will not become obsolete.

2024-02-05 11:21 UTC, jonat123 commented
@pijemcolu Maybe the sentence can just be removed, as it is already mentioned that they will be removed in the future in the dropdown 🤔

2024-02-06 08:00 UTC, pijemcolu commented on umbraco-cloud/set-up/project-settings/manage-hostnames/README.md
> +If you are using the [Former A and AAAA records](./#former-a-and-aaaa-records) consider changing them to the new A & AAAA records above as they will not become obsolete.
Applied the "shortening" suggestion.

2024-02-06 08:01 UTC, pijemcolu commented
> @pijemcolu Maybe the sentence can just be removed, as it is already mentioned that they will be removed in the future in the dropdown 🤔

I've removed the ending, that way it's visible immediately but the unclear ending is gone. Ready to merge now?

2024-02-06 09:36 UTC, jonat123 approved these changes

2024-02-06 09:36 UTC, jonat123 commented
sure thing, merging the PR :-)

2024-02-06 09:36 UTC, merged