Update Troubleshooting.md
umbraco/UmbracoDocs pull request #5844
Opened 2024-02-09 12:27 UTC by jesp209i

add text about removing `updating` marker

## Description

_What did you add/update/change?_

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

Cloud / CICD

## Deadline (if relevant)

no deadline

2024-02-09 14:15 UTC, alina-tincas commented
Hi @jesp209i thank you for the PR 🙌 

We will take a look at it as soon as we can 😊

2024-02-13 08:49 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +Once the leftover marker file is removed, you are ready to run your pipeline again.
```suggestion
Once the leftover marker file is removed, you run your pipeline again.
```

2024-02-13 08:49 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +In order to fix this issue, you would need to use [KUDU](../../power-tools/README.md) to remove the leftover marker file.
```suggestion
In order to fix this issue, you need to use [KUDU](../../power-tools/README.md) to remove the leftover marker file.
```

2024-02-13 08:49 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +The next time you try to deploy through your pipeline you encounter the error.
```suggestion
The next time you try to deploy through your pipeline you will encounter an error.
```

2024-02-13 08:49 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +In rare cases deployments fail, and the cloud infrastructure doesn't clean up correctly. This leaves behind the "updating" marker.
```suggestion
In rare cases deployments fail, and the cloud infrastructure doesn't clean up correctly. This leaves behind an "updating" marker.
```

2024-02-13 08:49 UTC, jonat123 requested changes
@jesp209i Thanks for the PR!

Looks good, just have a couple of suggestions 😄

2024-02-18 15:13 UTC, jesp209i commented
Great suggestions, thanks! - they have all been applied 👍

2024-02-19 08:29 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +
```suggestion
1. Access KUDU on the "left-most" environment
  * If you only have one environment you want the live environment
  * If you have more than one environment, you want the development environment

3. Navigate to `site` > `locks` folder  In there, there should be a file named `updating`

4. Remove the `updating` file.

```

2024-02-19 08:31 UTC, jonat123 approved these changes
@jesp209i Thanks for merging in my suggestions! :D 

Just noticed some minor things, and made suggestions for them and added them to speed up the process 😄

I will go ahead and merge in this PR!

2024-02-19 08:32 UTC, merged