Updated use of obsolete method
umbraco/UmbracoDocs pull request #5846
Opened 2024-02-10 11:06 UTC by oblongataconsultancy

Updated documentation to prevent it recommending the use of an obsolete method.

## Description

Removed reference to `AddUmbracoEFCoreContext` for V13 as this now marked `[Obsolete("Use AddUmbracoDbContext<T>(this IServiceCollection services, Action<DbContextOptionsBuilder>? optionsAction = null) instead.")]` in the latest release but the documentation doesn't reflect.

## Type of suggestion

* [ ] Typo/grammar fix
* [x] Updated outdated content
* [ ] New content
* [x] Updates related to a new version
* [ ] Other

## Product & version (if relevant)
V13

## Deadline (if relevant)

N/A

2024-02-10 11:06 UTC, oblongataconsultancy commented
Might want to consider additional documentation for users implementing SQLite where `UseSqlite` would be the preferred option over `UseSqlServer`?

2024-02-13 09:05 UTC, alina-tincas commented
Hi @oblongataconsultancy thank you for the PR 🙌 

We will take a look at it as soon as we can 🙏

2024-03-01 10:38 UTC, Zeegaan commented
Looks good from a dev standpoint, but as @oblongataconsultancy said, we should consider to also add how to do it for SQLite 😊

2024-03-07 14:30 UTC, alina-tincas requested changes
Thank you @Zeegaan for reviewing 🙌 

To make note for SQlite, how about adding a comment under it as suggested here? 🙈 
Also, @oblongataconsultancy would you be up for making this same change to v12 to make sure the content is consistent on all versions? 😊

2024-03-07 14:30 UTC, alina-tincas commented on 13/umbraco-cms/tutorials/getting-started-with-entity-framework-core.md
> +});
```suggestion
builder.Services.AddUmbracoDbContext<BlogContext>(options => 
{
    options.UseSqlServer("{YOUR CONNECTIONSTRING HERE}");
    //If you are using SQlite, replace UseSqlServer with UseSqlite
});
```

2024-03-07 14:30 UTC, alina-tincas commented on 13/umbraco-cms/tutorials/getting-started-with-entity-framework-core.md
> +});
```suggestion
builder.Services.AddUmbracoDbContext<BlogContext>(options => 
{
    options.UseSqlServer("{YOUR CONNECTIONSTRING HERE}");
    //If you are using SQlite, replace UseSqlServer with UseSqlite
});
```

2024-03-08 08:50 UTC, alina-tincas commented on 13/umbraco-cms/tutorials/getting-started-with-entity-framework-core.md
> +});
this seems to be repeating twice so in this case my suggestion would be to remove this above example 🤔

2024-03-15 08:30 UTC, alina-tincas commented
Hi @oblongataconsultancy as I have not heard from you in a while, I will go ahead and merge this PR and make the necessary changes afterwards 👍 

Thank you for again for contributing #h5YR 🙌

2024-03-15 08:30 UTC, alina-tincas approved these changes

2024-03-15 08:30 UTC, merged