Release notes for Forms 8.13.14, 10.5.4, 12.2.3 and 13.0.2 and Deploy 4.9.4, 10.3.4, 12.1.4 and 13.0.4
umbraco/UmbracoDocs pull request #5847
Opened 2024-02-12 11:34 UTC by AndyButland

## Description

Added release notes for Forms 8.13.14, 10.5.4, 12.2.3 and 13.0.2 and Deploy 4.9.4, 10.3.4, 12.1.4 and 13.0.4

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [X] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

Forms 8.13.14, 10.5.4, 12.2.3 and 13.0.2 and Deploy 4.9.4, 10.3.4, 12.1.4 and 13.0.4

## Deadline (if relevant)

By Thursday this week if possible please (doesn't matter if earlier).

2024-02-12 11:39 UTC, AndyButland commented
Linter reports " We prefer 'primary' over 'master.'" - but "master" [is the term still used in Umbraco for templates](https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-basic-website/creating-master-template-part-1).

2024-02-13 08:58 UTC, alina-tincas commented
Hi @AndyButland thank you for the PR 🙌 

We will take a look at it as soon as we can 😊

2024-02-13 10:40 UTC, eshanrnh requested changes
The PR looks great, @AndyButland 🙌 I've added a couple of suggestions.

2024-02-13 10:40 UTC, eshanrnh commented on 10/umbraco-forms/release-notes.md
> +* Update the copy form dialog to use standard CMS patterns for button state and disabling after click [#1121](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1121).
```suggestion
* Updated the copy form dialog to use standard CMS patterns for button state and disable it after clicking [#1121](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1121).
```

2024-02-13 10:40 UTC, eshanrnh commented on 10/umbraco-forms/release-notes.md
> +* Fixed display of validation error when a duplicate form field alias is created [#1150](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1152)
```suggestion
* Fixed display of validation error when a duplicate form field alias is created [#1152](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1152)
```

2024-02-13 10:40 UTC, eshanrnh commented on 10/umbraco-forms/release-notes.md
> +* Update the copy form dialog to use standard CMS patterns for button state and disabling after click [#1121](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1121).
```suggestion
* Updated the copy form dialog to use standard CMS patterns for button state and disable it after clicking [#1121](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1121).
```

2024-02-13 10:40 UTC, eshanrnh commented on 12/umbraco-forms/release-notes.md
> +* Ensured UI for the upload of a text file for a prevalue source only allows selection of expected .txt files.
```suggestion
* Ensured UI for the upload of a text file for a prevalue source only allows the selection of expected .txt files.
```

2024-02-13 10:40 UTC, eshanrnh commented on 10/umbraco-forms/release-notes.md
> +* Ensured UI for the upload of a text file for a prevalue source only allows selection of expected .txt files.
```suggestion
* Ensured UI for the upload of a text file for a prevalue source only allows the selection of expected .txt files.
```

2024-02-13 10:40 UTC, eshanrnh commented on 12/umbraco-forms/release-notes.md
> +* Fixed display of validation error when a duplicate form field alias is created [#1150](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1152)
```suggestion
* Fixed display of validation error when a duplicate form field alias is created [#1152](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1152)
```

2024-02-13 10:40 UTC, eshanrnh commented on 13/umbraco-forms/release-notes.md
> +* Ensured UI for the upload of a text file for a prevalue source only allows selection of expected .txt files.
```suggestion
* Ensured UI for the upload of a text file for a prevalue source only allows the selection of expected .txt files.
```

2024-02-13 10:40 UTC, eshanrnh commented on 13/umbraco-forms/release-notes.md
> +* Fixed display of validation error when a duplicate form field alias is created [#1150](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1152)
```suggestion
* Fixed display of validation error when a duplicate form field alias is created [#1152](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1152)
```

2024-02-13 10:42 UTC, AndyButland commented
All good with me, thanks - I've accepted the suggestions.

2024-02-13 14:22 UTC, eshanrnh approved these changes
Thanks for incorporating the suggestions. 🙌 Merging in the PR. 💪

2024-02-13 14:23 UTC, merged