Umbraco Commerce Docs Updates
umbraco/UmbracoDocs pull request #5881
Opened 2024-02-23 10:28 UTC by mattbrailsford

## Description

Fixing some broken links, and added a missing docs page for Realtime Shipping Rate setup

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [x] Other

## Product & version (if relevant)

v13

## Deadline (if relevant)

ASAP

2024-02-23 11:55 UTC, alina-tincas commented
Hi @mattbrailsford thank you for the PR 🙌 

We will review it as soon as we can 🙏

2024-02-26 10:46 UTC, eshanrnh requested changes
Hey @mattbrailsford 👋

Thanks for the PR. I have suggested few changes based on the style guide. Kindly let me know if it doesn't make sense to you.

2024-02-26 10:46 UTC, eshanrnh commented on 13/umbraco-commerce/reference/shipping/realtime-rate-shipping.md
> +## Configuration
```suggestion
## Configuring Realtime Rate Shipping

To configure Realtime Rate Shipping, follow these steps:
```

2024-02-26 10:46 UTC, eshanrnh commented on 13/umbraco-commerce/reference/shipping/realtime-rate-shipping.md
> +* Populate the shipping method name, alias, sku and optional image and tax rate
```suggestion
8. Enter the **Shipping Method Name**, **Alias**, **SKU**.
9. Select the tax class from the **Tax Class** dropdown list.
10. _[Optional]_ Upload an image.
```

2024-02-26 10:46 UTC, eshanrnh commented on 13/umbraco-commerce/reference/shipping/realtime-rate-shipping.md
> +* Enter any shipping provider API credentials required to connect to the shipping operators API
```suggestion
11. Enter the shipping provider's API credentials required to connect to the shipping operator's API.
```

2024-02-26 10:46 UTC, eshanrnh commented on 13/umbraco-commerce/reference/shipping/realtime-rate-shipping.md
> +* Configure the countries in this shipping method should be allowed in
```suggestion
12. Select the countries this shipping method should be allowed in.
13. Click **Save**.
```

2024-02-28 12:51 UTC, eshanrnh approved these changes
Merging it in.

2024-02-28 12:54 UTC, merged