Initial docs for Bellissima Routes
umbraco/UmbracoDocs pull request #6016
Opened 2024-04-09 21:59 UTC by enkelmedia

## Description

Added initial docs (needs review) for routes, I'm sure that there are more to this but figured that this is good start.

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)
Umbraco v14 new backoffice

2024-04-10 09:03 UTC, alina-tincas requested changes
Hi @enkelmedia thank you for the PR, much appreciated 🙌 

I have few suggestions, can you please take a look into them? 😊

2024-04-10 09:40 UTC, enkelmedia commented
Great feedback @alina-tincas! 

Thanks for the fixes! 

Let me know if you have other things that you would like to change =D

2024-04-10 10:19 UTC, alina-tincas commented on 14/umbraco-cms/extending-backoffice/routes.md
> +The order in which the routes are defined is important as the first match will be used so make sure to add more specific routes in the beginning.
fixinging lint error
```suggestion
The order in which the routes are defined is important as the first match will be used. So make sure to add more specific routes in the beginning.
```

2024-04-10 10:22 UTC, alina-tincas commented on 14/umbraco-cms/extending-backoffice/routes.md
> +Almost any component can host routable sub-components by defining a list of routes and render a `umb-router-slot` element. Let's assume we have a custom section with pathname `custom-section` and a `
```suggestion
Almost any component can host routable sub-components by defining a list of routes and render a `umb-router-slot` element. Let's assume we have a **custom section** with pathname `custom-section` and a **sectionView** with pathname `organization`. In this context we can create an element with routes, like this:
```

2024-04-10 10:23 UTC, alina-tincas approved these changes

2024-04-10 10:38 UTC, alina-tincas commented
I have nothing else to add for the moment, so I will merge this in 🙌

2024-04-10 10:38 UTC, merged

2024-04-10 12:33 UTC, enkelmedia commented
Great!

Maybe if @nielslyngsoe or someone from the team want to check that I’m not straight out lying about something 😂

2024-04-12 07:09 UTC, alina-tincas commented
I believe you are not lying 😆 I think the content makes sense hence I have approved and merged it. The team is quite busy until release at end of may so they will not be able to check this until then. It is however in our plan for the frontend team to check the new backoffice articles from extending-backoffice around final release or at least shortly after the release depending how busy they are. 👍