Update mapping
umbraco/UmbracoDocs pull request #6056
Opened 2024-04-26 12:20 UTC by erikjanwestendorp

## Description

Update mapping:
* [x] Remove 'totally
* [x] Remove 'very'
* [x] Change 'various ' to 'multiple'
* [x] Remove 'various'
* [x] Change 'i.e.' tot 'that is'
* [x] Write shorter sentences

## Type of suggestion

* [x] Styleguide

## Product & version (if relevant)
Umbraco CMS v10, 12, 13 & 14

2024-04-29 08:05 UTC, alina-tincas requested changes
Hi @erikjanwestendorp thank you for the PR 🙌 

All looks good except that somehow on v10 you have replaced 2 sentences with each other 🙈

2024-04-29 08:05 UTC, alina-tincas commented on 10/umbraco-cms/reference/mapping.md
> +UmbracoMapper replaced AutoMapper which was an external dependency. AutoMapper builds the mapping code dynamically, based upon mapping profiles, which are defined as C# expressions. UmbracoMapper rel
I suggest to leave back the sentence with **UmbracoMapper replaced AutoMapper**  in the hint note, as usually we list changes in hints note and in this case it makes sense to leave this in a hint note. Then with the sentence **UmbracoMapper was originally introduced** you can move this above the hint note or after the hint as it was💡

2024-05-01 06:24 UTC, alina-tincas reviewed
making those changes as it it only in 1 file

2024-05-01 06:24 UTC, alina-tincas commented on 10/umbraco-cms/reference/mapping.md
> +UmbracoMapper was originally introduced to solve some issues in the Umbraco core code. However, it is fine for anyone to use in their custom site implementations or packages as they wish.
```suggestion
UmbracoMapper replaced AutoMapper which was an external dependency. AutoMapper builds the mapping code dynamically, based upon mapping profiles, which are defined as C# expressions. UmbracoMapper relies on static code, that is, mappings need to be hand-written.
```

2024-05-01 06:24 UTC, alina-tincas commented on 10/umbraco-cms/reference/mapping.md
> +UmbracoMapper replaced AutoMapper which was an external dependency. AutoMapper builds the mapping code dynamically, based upon mapping profiles, which are defined as C# expressions. UmbracoMapper rel
```suggestion
UmbracoMapper was originally introduced to solve some issues in the Umbraco core code. However, it is fine for anyone to use in their custom site implementations or packages as they wish.
```

2024-05-01 06:25 UTC, alina-tincas approved these changes

2024-05-01 06:30 UTC, merged

2024-05-01 07:09 UTC, erikjanwestendorp commented
@alina-tincas Sorry! I completely forgot about this one 😅

2024-05-01 07:13 UTC, alina-tincas commented
No worries, I just noticed that I can also make the changes 🙈 🙌