Rewrite "Creating a user" as "Managing users"
umbraco/UmbracoDocs pull request #6177
Opened 2024-06-07 18:18 UTC by kjac

## Description

The ["Creating a user"](https://docs.umbraco.com/umbraco-cms/reference/management/services/create-a-new-user) article references obsolete and removed classes and service methods. It is also not at all about creating users - it is about adding users to groups 😆 

I have rewritten the entire article to get the code samples etc. up to date with V14. I have also opted to rename the article to "Managing Users". Eventually we could add more samples to this - for example, something about creating users? 😛 

## Type of suggestion

* [ ] Typo/grammar fix
* [x] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

V14

## Deadline (if relevant)

Whenever possible.

2024-06-10 07:24 UTC, jonat123 commented
@kjac Thanks for creating this PR 😄

We will review it as soon as we can 😊

2024-06-17 10:42 UTC, jonat123 commented on 14/umbraco-cms/reference/management/services/managing-users.md
> +1. We start by defining an interface for our implementation:
```suggestion
1. Start by defining an interface for our implementation:
```

2024-06-17 10:48 UTC, jonat123 commented on 14/umbraco-cms/reference/management/services/managing-users.md
> +3. To register the implementation, we need a Composer:
```suggestion
3. Register the implementation in a Composer:
```

2024-06-17 10:54 UTC, jonat123 requested changes
@kjac Looks good!

Just have two suggestions 😄

SInce you are removing an article, we also need a redirect in place.

Can you add the following line to the .gitbook.yaml file:
`reference/management/services/create-a-new-user: reference/management/services/managing-users.md`

you can find the file in the 14 -> umbraco-cms folder 😄

2024-06-17 12:34 UTC, kjac commented
Done @jonat123 👍

2024-06-18 07:12 UTC, jonat123 approved these changes
@kjac LGTM 💪

Merging it in!

2024-06-18 07:13 UTC, merged