Updated troubleshooting page for ci/cd
umbraco/UmbracoDocs pull request #6203
Opened 2024-06-20 13:52 UTC by andersreus

## Description
Updated troubleshooting page for ci/cd

_What did you add/update/change?_

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [x] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)
Cloud

## Deadline (if relevant)

_When should the content be published?_
After @jesp209i has reviewed the pr

2024-06-21 07:01 UTC, sofietoft commented
Thanks for the PR @andersreus ! 💪 

We'll make sure it's reviewed as soon as possible.

2024-06-22 11:36 UTC, jesp209i commented
Hi Docs team, 
@andersreus did a great job describing how to skip cloud-sync in Github.
I moved the section and added some extra context and a description on how to do similar things in Azure DevOps.

Ready for review

2024-06-26 08:59 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +## clous-sync
```suggestion
## cloud-sync
```

2024-06-26 10:34 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +The sample pipelines is naively trying to apply any change coming from the generated patch file on cloud. This doesn't always work and you might see an error similar to the following:
```suggestion
The sample pipelines are naively trying to apply any change coming from the generated patch file on cloud. This doesn't always work and you might see an error similar to the following:
```

2024-06-26 10:35 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +1. Cloud project package(s) has been auto upgraded, and that diff was already applied.
```suggestion
1. Cloud project package(s) has been auto-upgraded, and that diff was already applied.
```

2024-06-26 10:37 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +Once that has been done, you should run a new deployment, but without the `cloud-sync` step.
```suggestion
Once that has been done, you should run a new deployment without the `cloud-sync` step.
```

2024-06-26 10:38 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +4. Comment out the entire “cloud-sync” section and the “needs: cloud-sync” under “cloud-deployment”. An example is provided in the screenshot below.
```suggestion
1. Ensure your GitHub repository is up-to-date with any changes in your Umbraco Cloud environment.
2. Locate the main.yml file in the following directory: {projectname}\.github\workflows on tour local project.
3. Open the main.yml file in a text editor and navigate to the “jobs” section. 
4. Comment out the entire “cloud-sync” section and the “needs: cloud-sync” under “cloud-deployment”. An example is provided in the screenshot below.
```

2024-06-26 10:39 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +7. Uncomment the lines you previously commented out and make a new commit. Push these changes to GitHub.
```suggestion
5. Commit the changes, and push them to GitHub. This action will trigger a build and run the pipeline.
6. At this point, the pipeline should execute successfully and your changes will be pushed to Umbraco Cloud. If this is the case, proceed to the next step.
7. Uncomment the lines you previously commented out and make a new commit. Push these changes to GitHub. 
```

2024-06-26 10:44 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +  - Optional: If you add "[skip ci]" to the last commit message, to avoid automatically triggering the pipeline
```suggestion
  - Optional: Add "[skip ci]" to the last commit message, to avoid automatically triggering the pipeline
```

2024-06-26 10:45 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +2. Find the pipeline i Azure Devops.
```suggestion
2. Find the pipeline in Azure DevOps.
```

2024-06-26 10:46 UTC, jonat123 commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +5. Back in the "Run Pipeline" view, click on "Run".
```suggestion
5. Click on "Run" back in the "Run Pipeline" view.
```

2024-06-26 10:49 UTC, jonat123 requested changes
@andersreus The PR looks good!

I noticed a few things, and made you some suggestions 😊

2024-06-26 12:15 UTC, jesp209i commented
@jonat123 
I took the liberty to approve all of your awesome changes - thanks for making us look even better on text :+1:

2024-06-26 13:15 UTC, merged