Update cicd Troubleshooting.md
umbraco/UmbracoDocs pull request #6272
Opened 2024-07-17 09:33 UTC by jesp209i

## Description

Updates to troubleshooting

## Type of suggestion

* [ ] Typo/grammar fix
* [x] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

Cloud / CICD Flow

## Deadline (if relevant)

2024-07-17 12:57 UTC, eshanrnh requested changes
Thanks for the PR, @jesp209i 🙌 I've added some suggestions to clarify the sentences and fix the vale error.

Can you take a look and let me know if it doesn't look right?

2024-07-17 12:57 UTC, eshanrnh commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +We recommend that you align versions of the mentioned package(s) in your csproj-files to the higher version mentioned in the error for that package or a later version.
```suggestion
We recommend aligning the package versions in your _.csproj_ files with the higher version mentioned in the error for that package or a later version.
```

2024-07-17 12:57 UTC, eshanrnh commented on umbraco-cloud/set-up/project-settings/umbraco-cicd/Troubleshooting.md
> +Orphaned would be backup csproj files or files not referenced by the any of the main project-files nor referenced in a .sln-file.
```suggestion
Orphaned would be backup _.csproj_ files or files not referenced by any of the main project files nor referenced in a _.sln_ file.
```

2024-07-17 14:16 UTC, jesp209i commented
Great suggestions @eshanrnh 👍 
All suggestions accepted - thanks! 🌞

2024-07-18 08:03 UTC, eshanrnh approved these changes
Looks good to me, @jesp209i 🙌

2024-07-18 08:03 UTC, merged