Restructure import/export section and add grid layout and community package migrator documentation
umbraco/UmbracoDocs pull request #6285
Opened 2024-07-22 07:06 UTC by AndyButland

## Description

Restructured import/export section and add grid layout and community package migrator documentation.

This PR extends on and supersedes https://github.com/umbraco/UmbracoDocs/pull/6284 which can be closed.

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [X] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

Deploy 13.2.0-rc1 and 14.1.0-rc1
Deploy Contrib 4.4.0-rc1, 10.3.0-rc1, 12.2.0-rc1, 13.2.0-rc1 and 14.1.0-rc1

## Deadline (if relevant)

Can be reviewed and published at any time.

2024-07-22 12:27 UTC, eshanrnh commented
Thanks, @AndyButland for the PR 🙌 We will review it as soon as we can 💪

2024-07-23 08:29 UTC, eshanrnh requested changes
The PR looks good, @AndyButland 🙌 I'll incorporate the suggestions. 

Can you please add the v13 Summary file changes to v14 as well

2024-07-23 08:29 UTC, eshanrnh commented on 13/umbraco-deploy/deployment-workflow/import-with-migrations.md
> +We've also made available base implementations that you can use to build your own migrations. You may have a need to handle transfer of information between other obsolete and replacement property edi
```suggestion
We've also made available base implementations that you can use to build your own migrations. You may need to handle the transfer of information between other obsolete and replacement property editors that you have in your Umbraco application.
```

2024-07-23 08:29 UTC, eshanrnh commented on 13/umbraco-deploy/deployment-workflow/import-with-migrations.md
> +Migrators will run if you've registered them to, hence you can enable only the ones needed for your solution.
```suggestion
Migrators will run if you have registered them, so you can enable only the ones needed for your solution.
```

2024-07-23 08:29 UTC, eshanrnh commented on 13/umbraco-deploy/deployment-workflow/import-with-migrations.md
> +Open source migrators may be built by HQ or the community for property editors found in community packages. They will be made them available for [use](https://www.nuget.org/packages/Umbraco.Deploy.Co
```suggestion
Open source migrators may be built by HQ or the community for property editors found in community packages. They will be made available for [use](https://www.nuget.org/packages/Umbraco.Deploy.Contrib) and [review](https://github.com/umbraco/Umbraco.Deploy.Contrib/tree/v13/dev/src/Umbraco.Deploy.Contrib/Migrators) via the `Umbraco.Deploy.Contrib` package.
```

2024-07-23 08:29 UTC, eshanrnh commented on 13/umbraco-deploy/deployment-workflow/import-with-migrations.md
> +Thee implementations make use of the following conventions to migrate the data:
```suggestion
These implementations make use of the following conventions to migrate the data:
```

2024-07-23 08:29 UTC, eshanrnh commented on 13/umbraco-deploy/deployment-workflow/import-with-migrations.md
> +    - `Umbraco.MediaPicker3` - removes `url('` from the beginning and `')` from the end of the value (commonly used as modifier and added to the stored value), before trying to get the media item by
```suggestion
    - `Umbraco.MediaPicker3` - removes `url('` from the beginning and `')` from the end of the value (commonly used as a modifier and added to the stored value), before trying to get the media item by a path.
```

2024-07-23 08:29 UTC, eshanrnh commented on 13/umbraco-deploy/deployment-workflow/import-with-migrations.md
> +  - The amount of columns is copied over.
```suggestion
  - The number of columns is copied over.
```

2024-07-23 08:29 UTC, eshanrnh commented on 13/umbraco-deploy/deployment-workflow/import-with-migrations.md
> +In order to help writing your own migrations. we share here the source code of an example that ships with Umbraco Deploy. This migration converts Nested Content to Block List.
```suggestion
To help write your own migrations, we share the source code of an example that ships with Umbraco Deploy. This migration converts Nested Content to Block List.
```

2024-07-23 08:29 UTC, eshanrnh commented on 14/umbraco-deploy/deployment-workflow/import-export-v7.md
> +The import and export feature is available for Umbraco Deploy supporting Umbraco 8 and above. It's not been ported back to Umbraco 7, hence you can't trigger an export from there in the same way.
```suggestion
The import and export features are available for Umbraco Deploy supporting Umbraco 8 and above. It's not been ported back to Umbraco 7, hence you cannot trigger an export from there in the same way.
```

2024-07-23 08:29 UTC, eshanrnh commented on 14/umbraco-deploy/deployment-workflow/import-export-v7.md
> +We can however use this feature to help migrate from Umbraco 7 to a supported major version. It requires additional logic added to the Deploy Contrib project.
```suggestion
We can use this feature to help migrate from Umbraco 7 to a supported major version. However, it requires additional logic to be added to the Deploy Contrib project.
```

2024-07-23 08:29 UTC, eshanrnh commented on 14/umbraco-deploy/deployment-workflow/import-export-v7.md
> +Then you need to configure the legacy artifact type resolver and migratory.
```suggestion
- `Umbraco.Deploy.Contrib` for Umbraco 10.2, 12.1, 13.1 or later

Then you need to configure the legacy artifact type resolver and migratory.
```

2024-07-23 08:29 UTC, eshanrnh commented on 14/umbraco-deploy/deployment-workflow/import-export-v7.md
> +- Moving the invariant release and expire dates of content to the (culture variant) schedule property;
```suggestion
- Moving the invariant release and expiration dates of content to the (culture variant) schedule property;
```

2024-07-23 08:29 UTC, eshanrnh commented on 14/umbraco-deploy/deployment-workflow/import-export-v7.md
> +The following composer adds the required legacy artifact type resolver and migrators. It also adds a custom resolver that marks the specified Document Type alias `testElement` as element type. Elemen
```suggestion
The following composer adds the required legacy artifact type resolver and migrators. It also adds a custom resolver that marks the specified Document Type alias `testElement` as the element type. Element types are a concept added in Umbraco 8 and are required for Document Types that are used in Nested Content.
```

2024-07-23 08:29 UTC, eshanrnh commented on 14/umbraco-deploy/deployment-workflow/import-export-v7.md
> +It is recommended to first only import schema and schema files (by deselecting 'Content' and 'Content files' in the dialog). You can follow that by a complete import of all content and schema. The or
```suggestion
It is recommended to start by importing only the schema and schema files (by deselecting 'Content' and 'Content files' in the dialog). Then, you can proceed with importing all content and schema together. The order in which the artifacts are imported depends on their dependencies. By importing the schema first, we ensure that the schema is updated before any content is processed.
```

2024-07-23 08:29 UTC, eshanrnh commented on 14/umbraco-deploy/deployment-workflow/import-with-migrations.md
> +We've also made available base implementations that you can use to build your own migrations. You may have a need to handle transfer of information between other obsolete and replacement property edi
```suggestion
We've also made available base implementations that you can use to build your own migrations. You may need to handle the transfer of information between other obsolete and replacement property editors that you have in your Umbraco application.
```

2024-07-23 08:29 UTC, eshanrnh commented on 14/umbraco-deploy/deployment-workflow/import-with-migrations.md
> +Migrators will run if you've registered them to, hence you can enable only the ones needed for your solution.
```suggestion
Migrators will run if you have registered them, so you can enable only the ones needed for your solution.
```

2024-07-23 08:29 UTC, eshanrnh commented on 14/umbraco-deploy/deployment-workflow/import-with-migrations.md
> +Open source migrators may be built by HQ or the community for property editors found in community packages. They will be made them available for [use](https://www.nuget.org/packages/Umbraco.Deploy.Co
```suggestion
Open source migrators may be built by HQ or the community for property editors found in community packages. They will be made available for [use](https://www.nuget.org/packages/Umbraco.Deploy.Contrib) and [review](https://github.com/umbraco/Umbraco.Deploy.Contrib/tree/v13/dev/src/Umbraco.Deploy.Contrib/Migrators) via the `Umbraco.Deploy.Contrib` package.
```

2024-07-23 08:29 UTC, eshanrnh commented on 14/umbraco-deploy/deployment-workflow/import-with-migrations.md
> +Thee implementations make use of the following conventions to migrate the data:
```suggestion
These implementations make use of the following conventions to migrate the data:
```

2024-07-23 08:29 UTC, eshanrnh commented on 14/umbraco-deploy/deployment-workflow/import-with-migrations.md
> +    - `Umbraco.MediaPicker3` - removes `url('` from the beginning and `')` from the end of the value (commonly used as modifier and added to the stored value), before trying to get the media item by
```suggestion
    - `Umbraco.MediaPicker3` - removes `url('` from the beginning and `')` from the end of the value (commonly used as a modifier and added to the stored value), before trying to get the media item by a path.
```

2024-07-23 08:29 UTC, eshanrnh commented on 14/umbraco-deploy/deployment-workflow/import-with-migrations.md
> +  - The amount of columns is copied over.
```suggestion
  - The number of columns is copied over.
```

2024-07-23 08:29 UTC, eshanrnh commented on 14/umbraco-deploy/deployment-workflow/import-with-migrations.md
> +In order to help writing your own migrations. we share here the source code of an example that ships with Umbraco Deploy. This migration converts Nested Content to Block List.
```suggestion
To help write your own migrations, we share the source code of an example that ships with Umbraco Deploy. This migration converts Nested Content to Block List.
```

2024-07-23 08:56 UTC, AndyButland commented
Thanks @eshanrnh - I've updated the 14 summary file.

2024-07-23 09:28 UTC, eshanrnh approved these changes
Looks good to me. 🙌

2024-07-23 09:28 UTC, merged