Umbraco Commerce v14 Docs Updates
umbraco/UmbracoDocs pull request #6307
Opened 2024-07-29 14:27 UTC by mattbrailsford

## Description

Updated docs with changes from v14

## Type of suggestion

* [ ] Typo/grammar fix
* [x] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

Umbraco Commerce v14

## Deadline (if relevant)

TBD

2024-08-02 08:00 UTC, eshanrnh requested changes
Thanks for the PR, @mattbrailsford 🙌 I will incorporate most of the suggestions related to spelling/typos, styleguide, and so on.

Can you take a look at the rest of the suggestions - shortened couple of sentences to fix the vale error, is WIP Note required, and add Management API in the Summary file?

2024-08-02 08:33 UTC, eshanrnh commented on 14/umbraco-commerce/key-concepts/discount-rules-and-rewards.md
> +Our component is registered as a Property Editor UI, but without a defined scheme, it won't display in Umbraco backoffice as a pickable property editor for use on Document Types.
```suggestion
Without a defined scheme, the Property Editor UI will not display in Umbraco's backoffice as a pickable property editor for use on Document Types.
```

2024-08-05 08:19 UTC, mattbrailsford commented
I think that should be everything taken care of, but please let me know if I've missed anything

2024-08-05 08:56 UTC, eshanrnh approved these changes
Looks good to me, @mattbrailsford 🙌 Thanks for accepting the suggestion 💪

2024-08-05 08:56 UTC, merged