Added how to configure and use conditions on Workflows in Umbraco Forms
umbraco/UmbracoDocs pull request #6363
Opened 2024-08-19 14:41 UTC by eshanrnh

## Description

Added how to configure and use conditions on Workflows in Umbraco Forms

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

Forms v10,12,13,14

## Deadline (if relevant)

Anytime

2024-08-21 07:24 UTC, sofietoft requested changes
This is written as a guide.
Shouldn't it be added to a list instead? 🤔

2024-08-21 07:24 UTC, sofietoft commented on 10/umbraco-forms/editor/attaching-workflows/README.md
> +You can apply conditions to a workflow that trigger it only under specific circumstances. After adding the desired workflow type (for example, sending an email), you can add a condition to the workfl
```suggestion
You can apply conditions to a workflow to ensure it only triggers under specific circumstances. You could as an example enable a condition that enables sending an email only if an email is added.
```

2024-08-22 07:45 UTC, eshanrnh commented
@sofietoft, I wrote it as a guide to match the rest of the article. Changing this part to a step-by-step or list format means we'll have to change the entire article to keep it consistent 🙈 The other articles in the **Editor** section are also written as guides, so if we decide to change this article to a step-by-step or list format, we might have to consider those as well.

2024-08-22 08:13 UTC, sofietoft commented
> @sofietoft, I wrote it as a guide to match the rest of the article. Changing this part to a step-by-step or list format means we'll have to change the entire article to keep it consistent 🙈 The other articles in the **Editor** section are also written as guides, so if we decide to change this article to a step-by-step or list format, we might have to consider those as well.

Alright, that makes sense 😁

I do think thought that we at some point should ensure that whenever we have guides with steps, that the steps should be put into ordered lists. It's much easier to follow 💪🏻

2024-08-22 08:14 UTC, sofietoft approved these changes

2024-08-22 08:15 UTC, eshanrnh commented
Yup, I totally agree 💪 Merging this PR.

2024-08-22 08:16 UTC, merged