Adding descriptions
umbraco/UmbracoDocs pull request #6501
Opened 2024-10-02 17:37 UTC by Iqmaa

I added article descriptions to the markdown files 'cookies', 'Umbraco security hardening' and 'locking of users and password resets'

2024-10-03 10:27 UTC, eshanrnh requested changes
Thank you @Iqmaa for the PR 🙌 I've made a few comments—could you take a moment to check them out?

2024-10-03 10:27 UTC, eshanrnh commented on 14/umbraco-cms/reference/security/security-hardening.md
> +description: Learn how to strengthen the security of your Umbraco installation, and reduce the risk of unauthorised access.
```suggestion
description: Learn how to strengthen the security of your Umbraco installation, and reduce the risk of unauthorized access.
```

2024-10-03 10:27 UTC, eshanrnh commented on 14/umbraco-cms/reference/security/password-reset.md
> +description: Learn about the security features put in place to protect Umbraco users from unauthorised access and password breaches.
```suggestion
description: Learn about the security features put in place to protect Umbraco users from unauthorized access and password breaches.
```

2024-10-03 10:27 UTC, eshanrnh commented on 14/umbraco-cms/reference/security/cookies.md
> +description: Learn about the cookies required for accessing the umbraco backoffice and their purposes.
```suggestion
description: Learn about the cookies required for accessing the Umbraco Backoffice and their purposes.
```

2024-10-04 07:12 UTC, eshanrnh approved these changes
Looks good to me 🙌

2024-10-04 07:13 UTC, merged

2025-01-03 14:51 UTC, nul800sebastiaan commented
@Iqmaa Good day! You still have a few days to let us know what you want for Hacktoberfest 🎁, we'd love it if it was an active choice!
If you just want us to plant trees 🌳 then let me know or give the form a quick fill (only 2 fields to fill in for trees).
https://feedback.umbraco.com/umbraco-hacktoberfest-2024/

Thanks!