Add docker documentation for V14 and V15
umbraco/UmbracoDocs pull request #6588
Opened 2024-10-23 11:58 UTC by nikolajlauridsen

## Description

Updated the help output in the  `install-umbraco-with-templates.md` to include the new options, I also added an article about how you can run Umbraco locally with Docker using Docker Compose.  Note that this is only relevant for 14.3 and up, but I still added it to the V14 section as well.

## Type of suggestion

* [ ] Typo/grammar fix
* [X] Updated outdated content
* [X] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

CMS v14 and v15

2024-10-24 08:37 UTC, sofietoft requested changes
I've made some (okay, maybe a lot 🙈 ) suggestions to the new article.
Let me know if something doesn't look right.
I've only added comments to v14 - once they have been considered, the same changes should be added to v15 🙌 

Also, this is a new article.
It needs to be added to the SUMMARY file. Let me know if you prefer me doing this part 💪

2024-10-24 08:37 UTC, sofietoft commented on 14/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md
> +This setup is designed to be used for local development, and not for production.
```suggestion
To aid in developing Umbraco with additional services, the templates can provide the requisite files to run Umbraco with an SQL Server database in Docker. This setup is designed to be used for local development, and not for production.
```

2024-10-24 08:37 UTC, sofietoft commented on 14/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md
> +Now we need to add some additional files to make docker compose work. We can do this using the `umbraco-compose` template, passing the project name we specified earlier to the `-P` parameter:
Can we use steps here? 😇 

```suggestion
1. Create a folder to hold your project and enter that folder.

```bash
mkdir MyDockerProject
cd MyDockerProject
```

2. Create your Umbraco project using the Umbraco Templates, and remember to use the `--add-docker` flag to include the Docker files.

Conventionally this is named the same as the folder, but it is not a requirement.

```bash
dotnet new umbraco -n MyDockerProject --add-docker
```

Now we need to add some additional files to make docker compose work. We can do this using the `umbraco-compose` template, passing the project name we specified earlier to the `-P` parameter:
```

2024-10-24 08:37 UTC, sofietoft commented on 14/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md
> +  * docker-compose.yml
Use inline code for all file names.

```suggestion
* MyDockerProject
  * MyDockerProject
    * Typical project files
    * DockerFile
    * `.dockerignore`
  * `.env`
  * Database
    * DockerFile
    * `healthcheck.sh`
    * `setup.sql`
    * `startup.sh`
  * `docker-compose.yml`
```

2024-10-24 08:37 UTC, sofietoft commented on 14/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md
> +It also includes a .env file with the password for the database.
```suggestion
The project now includes docker files for both Umbraco and the SQL server database. 

It also includes additional scripts to launch and configure the database and a `.env` file with the database password.
```

2024-10-24 08:37 UTC, sofietoft commented on 14/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md
> +To run the project run the `docker compose up` command from the root of the project, same folder as `docker-compose.yml`.
```suggestion
To run the project use the `docker compose up` command in the root of the project files where the `docker-compose.yml` is.
```

2024-10-24 08:37 UTC, sofietoft commented on 14/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md
> +This command will build both the Umbraco and Sql Server images and launch them in the correct order, after a while the site will have booted and you can navigate to it in your browser like nomral on
```suggestion
This command will build both the Umbraco and SQL Server images and launch them in the correct order. When the site is booted, access it in your browser on `http://localhost:44372/`.
```

2024-10-24 08:37 UTC, sofietoft commented on 14/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md
> +There is some useful commands you can use to manage the docker containers:
```suggestion
There are some useful commands you can use to manage the docker containers:
```

2024-10-24 08:37 UTC, sofietoft commented on 14/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md
> +* `docker compose watch` This will start the containers and watch the default models folder, this means that if the project uses source code models builder the images automatically rebuilds and resta
```suggestion
* `docker compose down --volumes`: Delete your containers and the volumes they use. This is useful if you want to start from scratch.

{% hint style="warning" %}
Be careful with this command, as it deletes your database and all data in it.
{% endhint %}

* `docker compose up --build`: Rebuild the images and start the containers. This is useful if you have made changes to the project and want to see them reflected on the running site.
* `docker compose watch`: Start the containers and watch the default models folder. This means that if the project uses a source-code models builder the images are automatically rebuilt and restarts when you change the models.
```

2024-10-24 08:37 UTC, sofietoft commented on 14/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md
> +* /models
```suggestion
* `/wwwroot/media`
* `/wwwroot/scripts`
* `/wwwroot/css`
* `/Views`
* `/models`
```

2024-10-24 08:37 UTC, sofietoft commented on 14/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md
> +This is bad for production, however, for local development this means that the files necessary for development are available from outside the container in your IDE allowing you to effectively develop
```suggestion
This is not meant to be used in production.

For local development, however, this means that the files necessary for development are available from outside the container in your IDE. This allows development even though the project is running in docker.
```

2024-10-24 08:37 UTC, sofietoft commented on 14/umbraco-cms/fundamentals/setup/install/running-umbraco-on-docker-locally.md
> +* -p or --Port: Used to specify the port the site will run on, defaults to 44372
```suggestion
* `-P` or `--project-name`: The name of the project. This is required and used to set the correct paths in the docker-compose file.
* `-dbpw` or `--DatabasePasswor`: Used to specify the database password. This is stored in the `.env` file and defaults to: `Password1234`.
* `-p` or `--Port`: Used to specify the port the site will run on. Defaults to `44372`.
```

2024-10-28 09:44 UTC, nikolajlauridsen commented
Thanks 😄 I've applied the suggestions now, and good call on the list thing, didn't think of that 😄 

I didn't know about the summary file 😄 But yes that would be great if you could handle that, then I can see your commit for next time 😄

2024-10-30 09:38 UTC, merged