Update migrate-from-umarketingsuite.md
umbraco/UmbracoDocs pull request #6633
Opened 2024-11-07 12:47 UTC by Jette94

Added some changes to the guide after going through it

## Description

_What did you add/update/change?_

## Type of suggestion

* [ ] Typo/grammar fix
* [ ] Updated outdated content
* [ ] New content
* [ ] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

## Deadline (if relevant)

_When should the content be published?_

2024-11-07 14:11 UTC, sofietoft requested changes
Thanks @Jette94 !

I've added some suggestions and questions.
Please take a look when you have a minute.

2024-11-07 14:14 UTC, Jette94 commented on 13/umbraco-engage/upgrading/migrate-from-umarketingsuite.md
> +* The Cockpit Partial View has been moved, and needs to be changed to:
By replacing the uMarketingSuite Cockpit with Engage, the location will change - therefor you will need to change the path of the cockpit in the template :D

2024-11-07 14:14 UTC, Jette94 commented on 13/umbraco-engage/upgrading/migrate-from-umarketingsuite.md
> +3. Recompile all projects and ensure all dependencies are restored correctly.
I'm not sure why it shows changes here

2024-11-08 08:05 UTC, sofietoft reviewed
Thanks for considering the suggestions.

Did you see my suggestion to move the note about Cloud ABOVE the list?

2024-11-08 08:05 UTC, sofietoft commented on 13/umbraco-engage/upgrading/migrate-from-umarketingsuite.md
> +* The Cockpit Partial View has been moved, and needs to be changed to:
Alright! And which template is this exactly?
Just wondering if we should make that clearer, as currently it sounds like something needs to be moved to change a path 😅

2024-11-08 08:05 UTC, sofietoft commented on 13/umbraco-engage/upgrading/migrate-from-umarketingsuite.md
> +3. Recompile all projects and ensure all dependencies are restored correctly.
OK. I'll revert 💪

2024-11-08 08:05 UTC, sofietoft commented on 13/umbraco-engage/upgrading/migrate-from-umarketingsuite.md
> +{% hint style="info" %}
Will you make these changes, or should I? :)

2024-11-08 10:41 UTC, Jette94 commented on 13/umbraco-engage/upgrading/migrate-from-umarketingsuite.md
> +{% hint style="info" %}
Making them now :D

2024-11-08 10:43 UTC, Jette94 commented on 13/umbraco-engage/upgrading/migrate-from-umarketingsuite.md
> +* The Cockpit Partial View has been moved, and needs to be changed to:
It's the template for the page setup! If set up in a master template, that would be it. It needs to be in the bottom of the <body> tag

2024-11-12 07:43 UTC, sofietoft commented on 13/umbraco-engage/upgrading/migrate-from-umarketingsuite.md
> +* The Cockpit Partial View has been moved, and needs to be changed to:
Alright. Should we do something like this instead then:

"The Cockpit partial view has been moved, and any references should be changed to:"

2024-11-13 09:39 UTC, sofietoft approved these changes

2024-11-13 09:39 UTC, merged