UFM updates for v15
umbraco/UmbracoDocs pull request #6673
Opened 2024-11-14 16:07 UTC by leekelleher

## Description

Updated [UFM documentation](https://docs.umbraco.com/umbraco-cms/reference/umbraco-flavored-markdown) with the latest amends to support Umbraco 15.

In brief...
- Changes to the UFM prefixes (from a "marker" to an "alias)
- More detail on each available UFM component
- Documents UFM filters + details the available filters
- Guide to developing a custom UFM filter

## Type of suggestion

* [ ] Typo/grammar fix
* [x] Updated outdated content
* [x] New content
* [x] Updates related to a new version
* [ ] Other

## Product & version (if relevant)

Umbraco CMS 15.0.0

## Deadline (if relevant)

As soon as possible _(not urgent)_

2024-11-15 08:03 UTC, sofietoft requested changes
Thanks @leekelleher ! 💪 

I've made some suggestions for changes. Please take a look when you have minute.

I suggest that we avoid mentioning Umbraco versions. The docs are already versioned, so I don't think it necessary - at least not in these cases - to mention the specific version.

Hope it all makes sense!
Let me know if something doesn't 💪

2024-11-15 08:03 UTC, sofietoft commented on 15/umbraco-cms/reference/umbraco-flavored-markdown.md
> +Using the syntax `{myCustom: myCustomText}` would render the markup `<ufm-custom-component text="myCustomText"></ufm-custom-component>`. Then inside the `ufm-custom-component` component code, you can
```suggestion
Using the `{myCustom: myCustomText}` syntax would render the following markup: `<ufm-custom-component text="myCustomText"></ufm-custom-component>`. Inside the `ufm-custom-component` component code, you can perform any logic to render your required markup.
```

2024-11-15 08:03 UTC, sofietoft commented on 15/umbraco-cms/reference/umbraco-flavored-markdown.md
> +If you wish to develop your own custom UFM filter, you can use the `ufmFilter` extension type:
```suggestion
If you wish to develop custom UFM filter, you can use the `ufmFilter` extension type:
```

2024-11-15 08:03 UTC, sofietoft commented on 15/umbraco-cms/reference/umbraco-flavored-markdown.md
> +Using the syntax `{umbValue: headline | reverse}`, e.g. where `headline` having a value of `Hello world` would be transform to `dlrow olleH`.
```suggestion
Using the `{umbValue: headline | reverse}` syntax where `headline` having a value of `Hello world` would be transformed to `dlrow olleH`.
```

2024-11-15 08:03 UTC, sofietoft commented on 15/umbraco-cms/reference/umbraco-flavored-markdown.md
> +## Rendering UFM in your own components
```suggestion
## Rendering UFM in custom components
```

2024-11-19 11:55 UTC, leekelleher commented on 15/umbraco-cms/reference/umbraco-flavored-markdown.md
> +More UFM filters may be available in upcoming Umbraco releases.
True, let's remove that line. 💯

2024-11-19 11:57 UTC, leekelleher commented on 15/umbraco-cms/reference/umbraco-flavored-markdown.md
> +A list of available UFM filters is detailed below.
I didn't want the article to go into detail about the UFM Filters before covering the UFM Components (which should be the main focus). I'll merge in your edits and review at the overall page structure, (most likely moving UFM Filters lower down).

2024-11-19 12:02 UTC, leekelleher commented on 15/umbraco-cms/reference/umbraco-flavored-markdown.md
> +A list of available UFM filters is detailed below.
I've moved the list of UFM Filters higher up the page, to be with the description. 👍

2024-11-20 08:06 UTC, sofietoft commented on 15/umbraco-cms/reference/umbraco-flavored-markdown.md
> +As of Umbraco 15.0.0, the Content Name component supports the content-based pickers, e.g. Document Picker, Content Picker (formerly known as Multinode Treepicker) and Member Picker. Support for the a
Just one more suggestion:

```suggestion
The Content Name component supports content-based pickers, such as the Document Picker, Content Picker (formerly known as Multinode Treepicker), and Member Picker. Support for the advanced Media Picker will be available in an upcoming Umbraco release.
```

2024-11-20 08:10 UTC, leekelleher commented on 15/umbraco-cms/reference/umbraco-flavored-markdown.md
> +As of Umbraco 15.0.0, the Content Name component supports the content-based pickers, e.g. Document Picker, Content Picker (formerly known as Multinode Treepicker) and Member Picker. Support for the a
Super, thanks @sofietoft! 🙏

2024-11-20 08:11 UTC, merged